import type {
  FigmaAnalysis,
} from '@typefigma/analyzer';
import type { ElementorTemplate, GlobalSettings } from '@typefigma/elementor-mapper';

export interface ThemeFile {
  path: string;
  content: string;
}

export interface ThemeOptions {
  themeName: string;
  themeSlug: string;
  projectType: string;
}

export class WordPressFileBuilder {
  private options: ThemeOptions;
  private analysis: FigmaAnalysis;

  constructor(options: ThemeOptions, analysis: FigmaAnalysis) {
    this.options = options;
    this.analysis = analysis;
  }

  buildStyleCss(): string {
    return `/*
Theme Name: ${this.options.themeName}
Theme URI: https://example.com
Author: Auto Generated by TypeFigma
Author URI: https://typefigma.dev
Description: WordPress theme generated from Figma design. Type: ${this.analysis.projectType.type}
Version: 1.0.0
Requires at least: 6.0
Tested up to: 6.6
Requires PHP: 7.4
License: GPL v2 or later
License URI: https://www.gnu.org/licenses/gpl-2.0.html
Text Domain: ${this.options.themeSlug}
Tags: ${this.analysis.projectType.type === 'ecommerce' ? 'woocommerce, ' : ''}custom-colors, custom-logo, custom-menu, editor-style, featured-images, full-site-editing, theme-options, translation-ready

${this.analysis.projectType.type === 'ecommerce' ? `
WooCommerce:
- Products archive: /woocommerce/archive-product.php
- Single product: /woocommerce/single-product.php
` : ''}
*/`;
  }

  buildFunctionsPhp(): string {
    const hasWooCommerce = this.analysis.projectType.type === 'ecommerce';

    return `<?php
/**
 * ${this.options.themeName} - Functions & Setup
 *
 * @package ${this.options.themeSlug}
 */

// === Constants ===
define('${this.getConstant('VERSION')}', '1.0.0');
define('${this.getConstant('THEME_DIR')}', get_template_directory());
define('${this.getConstant('THEME_URI')}', get_template_directory_uri());

// === Theme Setup ===
add_action('after_setup_theme', function () {
    // Add theme support
    add_theme_support('title-tag');
    add_theme_support('post-thumbnails');
    add_theme_support('custom-logo', [
        'height'      => 60,
        'width'       => 200,
        'flex-height' => true,
        'flex-width'  => true,
    ]);
    add_theme_support('html5', [
        'search-form',
        'comment-form',
        'comment-list',
        'gallery',
        'caption',
        'style',
        'script',
    ]);
    add_theme_support('align-wide');
    add_theme_support('responsive-embeds');

    // Register nav menus
    register_nav_menus([
        'primary' => esc_html__('Primary Menu', '${this.options.themeSlug}'),
        'footer'  => esc_html__('Footer Menu', '${this.options.themeSlug}'),
    ]);

    ${hasWooCommerce ? `
    // WooCommerce support
    add_theme_support('woocommerce');
    add_theme_support('wc-product-gallery-zoom');
    add_theme_support('wc-product-gallery-lightbox');
    add_theme_support('wc-product-gallery-slider');
    ` : ''}
});

// === Enqueue Scripts & Styles ===
add_action('wp_enqueue_scripts', function () {
    // Theme stylesheet
    wp_enqueue_style(
        '${this.options.themeSlug}-global',
        ${this.getConstant('THEME_URI')} . '/assets/css/global.css',
        [],
        ${this.getConstant('VERSION')}
    );

    wp_enqueue_style(
        '${this.options.themeSlug}-components',
        ${this.getConstant('THEME_URI')} . '/assets/css/components.css',
        ['${this.options.themeSlug}-global'],
        ${this.getConstant('VERSION')}
    );

    // Theme JavaScript
    wp_enqueue_script(
        '${this.options.themeSlug}-theme',
        ${this.getConstant('THEME_URI')} . '/assets/js/theme.js',
        [],
        ${this.getConstant('VERSION')},
        true
    );
});

// === Elementor Support ===
add_action('plugins_loaded', function () {
    if (did_action('elementor/loaded')) {
        // Import saved templates on theme activation
        add_action('after_switch_theme', function () {
            ${this.options.themeSlug}_import_elementor_templates();
        });
    }
});

function ${this.options.themeSlug}_import_elementor_templates() {
    $templates_dir = ${this.getConstant('THEME_DIR')} . '/elementor/templates/';
    if (!is_dir($templates_dir)) return;

    $templates = glob($templates_dir . '*.json');
    if (!class_exists('\\\\Elementor\\\\TemplateLibrary\\\\Source_Local')) return;

    foreach ($templates as $template_file) {
        $template_data = json_decode(file_get_contents($template_file), true);
        if (!$template_data || !isset($template_data['title'])) continue;

        $existing = get_posts([
            'post_type'      => 'elementor_library',
            'title'          => $template_data['title'],
            'post_status'    => 'any',
            'posts_per_page' => 1,
        ]);

        if (!empty($existing)) continue;

        $post_id = wp_insert_post([
            'post_title'  => $template_data['title'],
            'post_type'   => 'elementor_library',
            'post_status' => 'publish',
            'meta_input'  => [
                '_elementor_template_type' => $template_data['type'] ?? 'page',
                '_elementor_edit_mode'     => 'builder',
                '_elementor_data'          => wp_json_encode($template_data['content']),
            ],
        ]);

        if ($post_id && isset($template_data['page_settings'])) {
            update_post_meta($post_id, '_elementor_page_settings', $template_data['page_settings']);
        }
    }
}

// === Customizer Settings ===
require_once ${this.getConstant('THEME_DIR')} . '/inc/customizer.php';

${hasWooCommerce ? `
// === WooCommerce Customizations ===
add_filter('loop_shop_columns', function () {
    return get_theme_mod('${this.options.themeSlug}_products_per_row', 4);
});

add_filter('loop_shop_per_page', function () {
    return get_theme_mod('${this.options.themeSlug}_products_per_page', 12);
});
` : ''}
`;
  }

  buildIndexPhp(): string {
    return `<?php
/**
 * Main template file
 *
 * @package ${this.options.themeSlug}
 */

get_header();
?>

<main id="primary" class="site-main">
    <div class="container">
        <?php
        if (have_posts()) :
            while (have_posts()) :
                the_post();
                ?>
                <article id="post-<?php the_ID(); ?>" <?php post_class(); ?>>
                    <header class="entry-header">
                        <?php the_title('<h1 class="entry-title">', '</h1>'); ?>
                    </header>

                    <div class="entry-content">
                        <?php the_content(); ?>
                    </div>
                </article>
                <?php
            endwhile;
        else :
            ?>
            <p><?php esc_html_e('No content found.', '${this.options.themeSlug}'); ?></p>
        <?php endif; ?>
    </div>
</main>

<?php
get_footer();
`;
  }

  buildHeaderPhp(): string {
    return `<!DOCTYPE html>
<html <?php language_attributes(); ?>>
<head>
    <meta charset="<?php bloginfo('charset'); ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?php wp_head(); ?>
</head>
<body <?php body_class(); ?>>
<?php
if (function_exists('wp_body_open')) {
    wp_body_open();
}
?>

<div id="page" class="site">
    <a class="skip-link screen-reader-text" href="#primary">
        <?php esc_html_e('Skip to content', '${this.options.themeSlug}'); ?>
    </a>

    <?php if (has_custom_logo() || has_nav_menu('primary')) : ?>
    <header id="masthead" class="site-header">
        <div class="container">
            <div class="header-inner">
                <div class="site-branding">
                    <?php
                    if (has_custom_logo()) {
                        the_custom_logo();
                    } else {
                        ?>
                        <a href="<?php echo esc_url(home_url('/')); ?>" rel="home">
                            <?php bloginfo('name'); ?>
                        </a>
                        <?php
                    }
                    ?>
                </div>

                <?php if (has_nav_menu('primary')) : ?>
                    <nav id="site-navigation" class="main-nav">
                        <?php
                        wp_nav_menu([
                            'theme_location' => 'primary',
                            'menu_class'     => 'nav-menu',
                            'container'      => false,
                            'fallback_cb'    => false,
                        ]);
                        ?>
                    </nav>
                <?php endif; ?>
            </div>
        </div>
    </header>
    <?php endif; ?>
`;
  }

  buildFooterPhp(): string {
    return `    <footer id="colophon" class="site-footer">
        <div class="container">
            <div class="footer-widgets">
                <?php
                for ($i = 1; $i <= 4; $i++) {
                    if (is_active_sidebar("footer-{$i}")) {
                        dynamic_sidebar("footer-{$i}");
                    }
                }
                ?>
            </div>

            <div class="footer-bottom">
                <p>&copy; <?php echo date('Y'); ?> <?php bloginfo('name'); ?>.
                    <?php esc_html_e('All rights reserved.', '${this.options.themeSlug}'); ?>
                </p>
            </div>
        </div>
    </footer>
</div>

<?php wp_footer(); ?>
</body>
</html>
`;
  }

  buildThemeJs(): string {
    return `/**
 * ${this.options.themeName} - Theme JavaScript
 */

document.addEventListener('DOMContentLoaded', function () {
    // Mobile menu toggle
    const toggle = document.querySelector('.mobile-menu-toggle');
    const nav = document.querySelector('.main-nav');

    if (toggle && nav) {
        toggle.addEventListener('click', function () {
            nav.classList.toggle('nav--open');
            toggle.classList.toggle('is-active');
        });
    }

    // Header scroll effect
    const header = document.querySelector('.site-header');
    if (header && header.classList.contains('header--sticky')) {
        let lastScroll = 0;

        window.addEventListener('scroll', function () {
            const currentScroll = window.pageYOffset;

            if (currentScroll > lastScroll && currentScroll > 100) {
                header.style.transform = 'translateY(-100%)';
            } else {
                header.style.transform = 'translateY(0)';
            }

            lastScroll = currentScroll;
        });
    }
});
`;
  }

  buildCustomizerPhp(): string {
    return `<?php
/**
 * Customizer Settings for ${this.options.themeName}
 *
 * @package ${this.options.themeSlug}
 */

add_action('customize_register', function ($wp_customize) {
    // === Colors Section ===
    $wp_customize->add_section('${this.options.themeSlug}_colors', [
        'title'    => esc_html__('Theme Colors', '${this.options.themeSlug}'),
        'priority' => 30,
    ]);

    $colors = [
        'primary_color'   => ['label' => 'Primary Color', 'default' => '${this.analysis.designTokens.colors.primary['500'] ?? '#3b82f6'}'],
        'secondary_color' => ['label' => 'Secondary Color', 'default' => '${this.analysis.designTokens.colors.secondary['500'] ?? '#8b5cf6'}'],
    ];

    foreach ($colors as $setting_key => $color) {
        $wp_customize->add_setting($setting_key, [
            'default'           => $color['default'],
            'sanitize_callback' => 'sanitize_hex_color',
        ]);

        $wp_customize->add_control(new WP_Customize_Color_Control(
            $wp_customize,
            $setting_key,
            [
                'label'   => esc_html__($color['label'], '${this.options.themeSlug}'),
                'section' => '${this.options.themeSlug}_colors',
            ]
        ));
    }

    // === Typography Section ===
    $wp_customize->add_section('${this.options.themeSlug}_typography', [
        'title'    => esc_html__('Typography', '${this.options.themeSlug}'),
        'priority' => 35,
    ]);

    $wp_customize->add_setting('heading_font', [
        'default' => 'Inter',
    ]);

    $wp_customize->add_control('heading_font', [
        'label'   => esc_html__('Heading Font', '${this.options.themeSlug}'),
        'section' => '${this.options.themeSlug}_typography',
        'type'    => 'select',
        'choices' => [
            'Inter'    => 'Inter',
            'Roboto'   => 'Roboto',
            'Open Sans' => 'Open Sans',
            'Lato'     => 'Lato',
            'Montserrat' => 'Montserrat',
        ],
    ]);

    $wp_customize->add_setting('body_font', [
        'default' => 'Inter',
    ]);

    $wp_customize->add_control('body_font', [
        'label'   => esc_html__('Body Font', '${this.options.themeSlug}'),
        'section' => '${this.options.themeSlug}_typography',
        'type'    => 'select',
        'choices' => [
            'Inter'    => 'Inter',
            'Roboto'   => 'Roboto',
            'Open Sans' => 'Open Sans',
            'Lato'     => 'Lato',
            'Montserrat' => 'Montserrat',
        ],
    ]);

    ${this.analysis.projectType.type === 'ecommerce' ? `
    // === Shop Layout Section ===
    if (class_exists('WooCommerce')) {
        $wp_customize->add_section('${this.options.themeSlug}_shop', [
            'title'    => esc_html__('Shop Layout', '${this.options.themeSlug}'),
            'priority' => 40,
        ]);

        $wp_customize->add_setting('${this.options.themeSlug}_products_per_row', [
            'default' => 4,
        ]);

        $wp_customize->add_control('${this.options.themeSlug}_products_per_row', [
            'label'   => esc_html__('Products per row', '${this.options.themeSlug}'),
            'section' => '${this.options.themeSlug}_shop',
            'type'    => 'number',
            'input_attrs' => [
                'min' => 2,
                'max' => 6,
            ],
        ]);

        $wp_customize->add_setting('${this.options.themeSlug}_products_per_page', [
            'default' => 12,
        ]);

        $wp_customize->add_control('${this.options.themeSlug}_products_per_page', [
            'label'   => esc_html__('Products per page', '${this.options.themeSlug}'),
            'section' => '${this.options.themeSlug}_shop',
            'type'    => 'number',
        ]);
    }
    ` : ''}
});
`;
  }

  buildWooArchivePhp(): string {
    return `<?php
/**
 * WooCommerce Archive Product Template
 *
 * @package ${this.options.themeSlug}
 */

get_header('shop');
?>

<main id="primary" class="site-main">
    <div class="container">
        <?php
        /**
         * Hook: woocommerce_before_main_content
         */
        do_action('woocommerce_before_main_content');
        ?>

        <header class="woocommerce-products-header">
            <?php if (apply_filters('woocommerce_show_page_title', true)) : ?>
                <h1 class="woocommerce-products-header__title page-title">
                    <?php woocommerce_page_title(); ?>
                </h1>
            <?php endif; ?>

            <?php
            /**
             * Hook: woocommerce_archive_description
             */
            do_action('woocommerce_archive_description');
            ?>
        </header>

        <?php
        if (woocommerce_product_loop()) {
            /**
             * Hook: woocommerce_before_shop_loop
             */
            do_action('woocommerce_before_shop_loop');

            woocommerce_product_loop_start();

            if (wc_get_loop_prop('total')) {
                while (have_posts()) {
                    the_post();
                    /**
                     * Hook: woocommerce_shop_loop
                     */
                    do_action('woocommerce_shop_loop');

                    wc_get_template_part('content', 'product');
                }
            }

            woocommerce_product_loop_end();

            /**
             * Hook: woocommerce_after_shop_loop
             */
            do_action('woocommerce_after_shop_loop');
        } else {
            /**
             * Hook: woocommerce_no_products_found
             */
            do_action('woocommerce_no_products_found');
        }

        /**
         * Hook: woocommerce_after_main_content
         */
        do_action('woocommerce_after_main_content');
        ?>
    </div>
</main>

<?php
get_footer('shop');
`;
  }

  buildWooSinglePhp(): string {
    return `<?php
/**
 * WooCommerce Single Product Template
 *
 * @package ${this.options.themeSlug}
 */

get_header('shop');
?>

<main id="primary" class="site-main">
    <div class="container">
        <?php
        /**
         * Hook: woocommerce_before_main_content
         */
        do_action('woocommerce_before_main_content');
        ?>

        <?php
        while (have_posts()) :
            the_post();

            wc_get_template_part('content', 'single-product');
        endwhile;
        ?>

        <?php
        /**
         * Hook: woocommerce_after_main_content
         */
        do_action('woocommerce_after_main_content');
        ?>
    </div>
</main>

<?php
get_footer('shop');
`;
  }

  buildElementorJson(template: ElementorTemplate): string {
    return JSON.stringify(template, null, 2);
  }

  buildGlobalSettingsJson(settings: GlobalSettings): string {
    return JSON.stringify(settings, null, 2);
  }

  getAllFiles(
    elementorTemplates: ElementorTemplate[],
    globalSettings: GlobalSettings,
    codeGen: { globalCss: string; componentsCss: string },
  ): ThemeFile[] {
    const files: ThemeFile[] = [
      { path: 'style.css', content: this.buildStyleCss() },
      { path: 'functions.php', content: this.buildFunctionsPhp() },
      { path: 'index.php', content: this.buildIndexPhp() },
      { path: 'header.php', content: this.buildHeaderPhp() },
      { path: 'footer.php', content: this.buildFooterPhp() },
      { path: 'assets/css/global.css', content: codeGen.globalCss },
      { path: 'assets/css/components.css', content: codeGen.componentsCss },
      { path: 'assets/js/theme.js', content: this.buildThemeJs() },
      { path: 'inc/customizer.php', content: this.buildCustomizerPhp() },
      { path: 'elementor/global-settings.json', content: this.buildGlobalSettingsJson(globalSettings) },
    ];

    for (const template of elementorTemplates) {
      files.push({
        path: `elementor/templates/${template.type}.json`,
        content: this.buildElementorJson(template),
      });
    }

    if (this.analysis.projectType.type === 'ecommerce') {
      files.push(
        { path: 'woocommerce/archive-product.php', content: this.buildWooArchivePhp() },
        { path: 'woocommerce/single-product.php', content: this.buildWooSinglePhp() },
      );
    }

    return files;
  }

  private getConstant(suffix: string): string {
    return strtoupper(this.options.themeSlug) + '_' + suffix;
  }
}

function strtoupper(s: string): string {
  return s.replace(/-/g, '_').toUpperCase();
}
