import type {
  FigmaAnalysis,
} from '@typefigma/analyzer';
import type { ElementorTemplate, GlobalSettings } from '@typefigma/elementor-mapper';
import { WpBlockGenerator, ThemeJsonGenerator } from '@typefigma/code-generator';
import type { GeneratedCode, BlockPattern } from '@typefigma/code-generator';
import { AdminPanelGenerator } from './config-panel.js';
import type { FontFamilyEntry } from './font-manager.js';
import * as zlib from 'zlib';

export interface ThemeFile {
  path: string;
  content: string | Buffer;
}

export interface ThemeOptions {
  themeName: string;
  themeSlug: string;
  projectType: string;
}

export interface FontOption {
  name: string;
  source: 'google' | 'local';
  weights?: number[];
  styles?: ('normal' | 'italic')[];
  file?: string;
  buffer?: Buffer;
}

export interface ThemeFontConfig {
  families: FontOption[];
}

export class WordPressFileBuilder {
  private options: ThemeOptions;
  private analysis: FigmaAnalysis;

  constructor(options: ThemeOptions, analysis: FigmaAnalysis) {
    this.options = options;
    this.analysis = analysis;
  }

  buildStyleCss(): string {
    return `/*
Theme Name: ${this.options.themeName}
Theme URI: https://example.com
Author: Auto Generated by TypeFigma
Author URI: https://typefigma.dev
Description: WordPress theme for ${this.analysis.projectType.type} websites
Version: 1.0.0
Requires at least: 6.0
Tested up to: 6.6
Requires PHP: 7.4
License: GPL v2 or later
License URI: https://www.gnu.org/licenses/gpl-2.0.html
Text Domain: ${this.options.themeSlug}
Tags: ${this.analysis.projectType.type === 'ecommerce' ? 'woocommerce, ' : ''}custom-colors, custom-logo, custom-menu, editor-style, featured-images, full-site-editing, theme-options, translation-ready

${this.analysis.projectType.type === 'ecommerce' ? `
WooCommerce:
- Products archive: /woocommerce/archive-product.php
- Single product: /woocommerce/single-product.php
` : ''}
*/`;
  }

  buildFunctionsPhp(): string {
    const hasWooCommerce = this.analysis.projectType.type === 'ecommerce';

    return `<?php
/**
 * ${this.options.themeName} - Functions & Setup
 *
 * @package ${this.options.themeSlug}
 */

// === Constants ===
define('${this.getConstant('VERSION')}', '1.0.0');
define('${this.getConstant('THEME_DIR')}', get_template_directory());
define('${this.getConstant('THEME_URI')}', get_template_directory_uri());

// === Load Modules ===
$fonts_file = ${this.getConstant('THEME_DIR')} . '/inc/fonts.php';
if (file_exists($fonts_file)) {
    require_once $fonts_file;
}

// === Theme Setup ===
add_action('after_setup_theme', function () {
    // Add theme support
    add_theme_support('title-tag');
    add_theme_support('post-thumbnails');
    add_theme_support('custom-logo', [
        'height'      => 60,
        'width'       => 200,
        'flex-height' => true,
        'flex-width'  => true,
    ]);
    add_theme_support('html5', [
        'search-form',
        'comment-form',
        'comment-list',
        'gallery',
        'caption',
        'style',
        'script',
    ]);
    add_theme_support('align-wide');
    add_theme_support('responsive-embeds');

    // Register nav menus
    register_nav_menus([
        'primary' => esc_html__('Primary Menu', '${this.options.themeSlug}'),
        'footer'  => esc_html__('Footer Menu', '${this.options.themeSlug}'),
    ]);

    ${hasWooCommerce ? `
    // WooCommerce support
    add_theme_support('woocommerce');
    add_theme_support('wc-product-gallery-zoom');
    add_theme_support('wc-product-gallery-lightbox');
    add_theme_support('wc-product-gallery-slider');
    ` : ''}
});

// === Enqueue Scripts & Styles ===
add_action('wp_enqueue_scripts', function () {
    // Theme stylesheet
    wp_enqueue_style(
        '${this.options.themeSlug}-global',
        ${this.getConstant('THEME_URI')} . '/assets/css/global.css',
        [],
        ${this.getConstant('VERSION')}
    );

    wp_enqueue_style(
        '${this.options.themeSlug}-components',
        ${this.getConstant('THEME_URI')} . '/assets/css/components.css',
        ['${this.options.themeSlug}-global'],
        ${this.getConstant('VERSION')}
    );

    // Theme JavaScript
    wp_enqueue_script(
        '${this.options.themeSlug}-theme',
        ${this.getConstant('THEME_URI')} . '/assets/js/theme.js',
        [],
        ${this.getConstant('VERSION')},
        true
    );

${hasWooCommerce ? `
    // WooCommerce styles
    wp_enqueue_style(
        '${this.options.themeSlug}-woocommerce',
        ${this.getConstant('THEME_URI')} . '/assets/css/woocommerce.css',
        ['${this.options.themeSlug}-global'],
        ${this.getConstant('VERSION')}
    );` : ''}
});

// === Elementor Support ===
if (!class_exists('\\\\Elementor\\\\Plugin')) {
    add_action('admin_notices', function () {
        ?>
        <div class="notice notice-warning is-dismissible">
            <p><?php esc_html_e('This theme requires Elementor to be installed and activated.', '${this.options.themeSlug}'); ?></p>
        </div>
        <?php
    });
}

add_action('plugins_loaded', function () {
    if (did_action('elementor/loaded')) {
        // Import saved templates on theme activation
        add_action('after_switch_theme', function () {
            ${this.options.themeSlug}_import_elementor_templates();
        });
    }
});

function ${this.options.themeSlug}_import_elementor_templates() {
    $templates_dir = ${this.getConstant('THEME_DIR')} . '/elementor/templates/';
    if (!is_dir($templates_dir)) return;

    $templates = glob($templates_dir . '*.json');
    if (!class_exists('\\\\Elementor\\\\TemplateLibrary\\\\Source_Local')) return;

    foreach ($templates as $template_file) {
        $template_data = json_decode(file_get_contents($template_file), true);
        if (!$template_data || !isset($template_data['title'])) continue;

        $existing = get_posts([
            'post_type'      => 'elementor_library',
            'title'          => $template_data['title'],
            'post_status'    => 'any',
            'posts_per_page' => 1,
        ]);

        if (!empty($existing)) continue;

        $post_id = wp_insert_post([
            'post_title'  => $template_data['title'],
            'post_type'   => 'elementor_library',
            'post_status' => 'publish',
            'meta_input'  => [
                '_elementor_template_type' => $template_data['type'] ?? 'page',
                '_elementor_edit_mode'     => 'builder',
                '_elementor_data'          => wp_json_encode($template_data['content']),
            ],
        ]);

        if ($post_id && isset($template_data['page_settings'])) {
            update_post_meta($post_id, '_elementor_page_settings', $template_data['page_settings']);
        }
    }
}

// === Register Sidebars ===
add_action('widgets_init', function () {
    register_sidebar([
        'name'          => esc_html__('Sidebar', '${this.options.themeSlug}'),
        'id'            => 'sidebar-1',
        'description'   => esc_html__('Main sidebar widget area', '${this.options.themeSlug}'),
        'before_widget' => '<section id="%1$s" class="widget %2$s">',
        'after_widget'  => '</section>',
        'before_title'  => '<h3 class="widget-title">',
        'after_title'   => '</h3>',
    ]);

    for ($i = 1; $i <= 4; $i++) {
        register_sidebar([
            'name'          => sprintf(esc_html__('Footer %d', '${this.options.themeSlug}'), $i),
            'id'            => "footer-{$i}",
            'description'   => sprintf(esc_html__('Footer widget area %d', '${this.options.themeSlug}'), $i),
            'before_widget' => '<div id="%1$s" class="footer-widget %2$s">',
            'after_widget'  => '</div>',
            'before_title'  => '<h4 class="footer-widget-title">',
            'after_title'   => '</h4>',
        ]);
    }
});

// === Customizer Settings ===
    require_once ${this.getConstant('THEME_DIR')} . '/inc/customizer.php';

// === Elementor Widgets ===
if (did_action('elementor/loaded')) {
    require_once ${this.getConstant('THEME_DIR')} . '/inc/elementor-widgets.php';
}

${hasWooCommerce ? `
// === WooCommerce Customizations ===
add_filter('loop_shop_columns', function () {
    return get_theme_mod('${this.options.themeSlug}_products_per_row', 4);
});

add_filter('loop_shop_per_page', function () {
    return get_theme_mod('${this.options.themeSlug}_products_per_page', 12);
});
` : ''}
`;
  }

  buildIndexPhp(): string {
    return `<?php
/**
 * Main template file
 *
 * @package ${this.options.themeSlug}
 */

get_header();
?>

<main id="primary" class="site-main">
    <div class="container">
        <?php
        if (have_posts()) :
            while (have_posts()) :
                the_post();
                ?>
                <article id="post-<?php the_ID(); ?>" <?php post_class(); ?>>
                    <header class="entry-header">
                        <?php the_title('<h1 class="entry-title">', '</h1>'); ?>
                    </header>

                    <div class="entry-content">
                        <?php the_content(); ?>
                    </div>
                </article>
                <?php
            endwhile;
        else :
            ?>
            <p><?php esc_html_e('No content found.', '${this.options.themeSlug}'); ?></p>
        <?php endif; ?>
    </div>
</main>

<?php
get_footer();
`;
  }

  buildHeaderPhp(): string {
    return `<!DOCTYPE html>
<html <?php language_attributes(); ?>>
<head>
    <meta charset="<?php bloginfo('charset'); ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?php wp_head(); ?>
</head>
<body <?php body_class(); ?>>
<?php
if (function_exists('wp_body_open')) {
    wp_body_open();
}
?>

<div id="page" class="site">
    <a class="skip-link screen-reader-text" href="#primary">
        <?php esc_html_e('Skip to content', '${this.options.themeSlug}'); ?>
    </a>

    <?php if (has_custom_logo() || has_nav_menu('primary')) : ?>
    <header id="masthead" class="site-header">
        <div class="container">
            <div class="header-inner">
                <div class="site-branding">
                    <?php
                    if (has_custom_logo()) {
                        the_custom_logo();
                    } else {
                        ?>
                        <a href="<?php echo esc_url(home_url('/')); ?>" rel="home">
                            <?php bloginfo('name'); ?>
                        </a>
                        <?php
                    }
                    ?>
                </div>

                <?php if (has_nav_menu('primary')) : ?>
                    <nav id="site-navigation" class="main-nav">
                        <?php
                        wp_nav_menu([
                            'theme_location' => 'primary',
                            'menu_class'     => 'nav-menu',
                            'container'      => false,
                            'fallback_cb'    => false,
                        ]);
                        ?>
                    </nav>
                <?php endif; ?>
            </div>
        </div>
    </header>
    <?php endif; ?>
`;
  }

  buildSinglePhp(): string {
    return `<?php
/**
 * Single Post Template
 *
 * @package ${this.options.themeSlug}
 */

get_header();
?>

<main id="primary" class="site-main">
    <div class="container">
        <?php
        while (have_posts()) :
            the_post();
            ?>
            <article id="post-<?php the_ID(); ?>" <?php post_class(); ?>>
                <?php if (has_post_thumbnail()) : ?>
                    <div class="post-thumbnail">
                        <?php the_post_thumbnail('large'); ?>
                    </div>
                <?php endif; ?>

                <header class="entry-header">
                    <h1 class="entry-title"><?php the_title(); ?></h1>
                    <div class="entry-meta">
                        <span class="posted-by"><?php esc_html_e('By', '${this.options.themeSlug}'); ?> <?php the_author_posts_link(); ?></span>
                        <span class="posted-on"><?php echo get_the_date(); ?></span>
                        <span class="post-categories"><?php the_category(', '); ?></span>
                    </div>
                </header>

                <div class="entry-content">
                    <?php the_content(); ?>
                    <?php
                    wp_link_pages([
                        'before' => '<div class="page-links">' . esc_html__('Pages:', '${this.options.themeSlug}'),
                        'after'  => '</div>',
                    ]);
                    ?>
                </div>

                <footer class="entry-footer">
                    <?php the_tags('<span class="tags-links">' . esc_html__('Tagged:', '${this.options.themeSlug}') . ' ', ', ', '</span>'); ?>
                </footer>

                <?php
                if (comments_open() || get_comments_number()) {
                    comments_template();
                }
                ?>
            </article>
            <?php
        endwhile;
        ?>
    </div>
</main>

<?php
get_sidebar();
get_footer();
`;
  }

  buildPagePhp(): string {
    return `<?php
/**
 * Page Template
 *
 * @package ${this.options.themeSlug}
 */

get_header();
?>

<main id="primary" class="site-main">
    <div class="container">
        <?php
        while (have_posts()) :
            the_post();
            ?>
            <article id="post-<?php the_ID(); ?>" <?php post_class(); ?>>
                <?php if (has_post_thumbnail()) : ?>
                    <div class="page-thumbnail">
                        <?php the_post_thumbnail('large'); ?>
                    </div>
                <?php endif; ?>

                <header class="entry-header">
                    <h1 class="entry-title"><?php the_title(); ?></h1>
                </header>

                <div class="entry-content">
                    <?php the_content(); ?>
                    <?php
                    wp_link_pages([
                        'before' => '<div class="page-links">' . esc_html__('Pages:', '${this.options.themeSlug}'),
                        'after'  => '</div>',
                    ]);
                    ?>
                </div>
            </article>
            <?php
        endwhile;
        ?>
    </div>
</main>

<?php
get_footer();
`;
  }

  buildArchivePhp(): string {
    return `<?php
/**
 * Archive Template
 *
 * @package ${this.options.themeSlug}
 */

get_header();
?>

<main id="primary" class="site-main">
    <div class="container">
        <header class="archive-header">
            <h1 class="archive-title">
                <?php
                if (is_category()) {
                    single_cat_title();
                } elseif (is_tag()) {
                    single_tag_title();
                } elseif (is_author()) {
                    the_archive_title();
                } elseif (is_date()) {
                    the_archive_title();
                } else {
                    the_archive_title();
                }
                ?>
            </h1>
            <?php the_archive_description('<div class="archive-description">', '</div>'); ?>
        </header>

        <?php if (have_posts()) : ?>
            <div class="archive-posts">
                <?php
                while (have_posts()) :
                    the_post();
                    ?>
                    <article id="post-<?php the_ID(); ?>" <?php post_class('archive-post'); ?>>
                        <?php if (has_post_thumbnail()) : ?>
                            <a href="<?php the_permalink(); ?>" class="post-thumbnail-link">
                                <?php the_post_thumbnail('medium'); ?>
                            </a>
                        <?php endif; ?>

                        <h2 class="entry-title">
                            <a href="<?php the_permalink(); ?>"><?php the_title(); ?></a>
                        </h2>

                        <div class="entry-meta">
                            <span><?php echo get_the_date(); ?></span>
                            <span><?php the_author_posts_link(); ?></span>
                        </div>

                        <div class="entry-excerpt">
                            <?php the_excerpt(); ?>
                        </div>

                        <a href="<?php the_permalink(); ?>" class="read-more">
                            <?php esc_html_e('Read More', '${this.options.themeSlug}'); ?>
                        </a>
                    </article>
                    <?php
                endwhile;
                ?>
            </div>

            <div class="pagination">
                <?php the_posts_pagination(); ?>
            </div>
        <?php else : ?>
            <p><?php esc_html_e('No posts found.', '${this.options.themeSlug}'); ?></p>
        <?php endif; ?>
    </div>
</main>

<?php
get_sidebar();
get_footer();
`;
  }

  buildSidebarPhp(): string {
    return `<?php
/**
 * Sidebar Template
 *
 * @package ${this.options.themeSlug}
 */

if (!is_active_sidebar('sidebar-1')) {
    return;
}
?>

<aside id="secondary" class="widget-area site-sidebar" role="complementary">
    <?php dynamic_sidebar('sidebar-1'); ?>
</aside>
`;
  }

  build404Php(): string {
    return `<?php
/**
 * 404 Template
 *
 * @package ${this.options.themeSlug}
 */

get_header();
?>

<main id="primary" class="site-main">
    <div class="container">
        <section class="error-404 not-found">
            <header class="page-header">
                <h1 class="page-title"><?php esc_html_e('Page Not Found', '${this.options.themeSlug}'); ?></h1>
            </header>

            <div class="page-content">
                <p><?php esc_html_e('The page you are looking for might have been removed, had its name changed, or is temporarily unavailable.', '${this.options.themeSlug}'); ?></p>

                <div class="search-form-wrapper">
                    <?php get_search_form(); ?>
                </div>

                <a href="<?php echo esc_url(home_url('/')); ?>" class="btn btn-primary">
                    <?php esc_html_e('Back to Home', '${this.options.themeSlug}'); ?>
                </a>
            </div>
        </section>
    </div>
</main>

<?php
get_footer();
`;
  }

  buildSearchPhp(): string {
    return `<?php
/**
 * Search Results Template
 *
 * @package ${this.options.themeSlug}
 */

get_header();
?>

<main id="primary" class="site-main">
    <div class="container">
        <header class="search-header">
            <h1 class="search-title">
                <?php
                printf(
                    esc_html__('Search Results for: %s', '${this.options.themeSlug}'),
                    '<span>' . get_search_query() . '</span>'
                );
                ?>
            </h1>
        </header>

        <?php if (have_posts()) : ?>
            <div class="search-results">
                <?php
                while (have_posts()) :
                    the_post();
                    ?>
                    <article id="post-<?php the_ID(); ?>" <?php post_class('search-result'); ?>>
                        <h2 class="entry-title">
                            <a href="<?php the_permalink(); ?>"><?php the_title(); ?></a>
                        </h2>

                        <div class="entry-excerpt">
                            <?php the_excerpt(); ?>
                        </div>

                        <div class="entry-meta">
                            <span><?php echo get_the_date(); ?></span>
                            <span><?php the_category(', '); ?></span>
                        </div>
                    </article>
                    <?php
                endwhile;
                ?>
            </div>

            <div class="pagination">
                <?php the_posts_pagination(); ?>
            </div>
        <?php else : ?>
            <div class="no-results">
                <p><?php esc_html_e('No results found for your search.', '${this.options.themeSlug}'); ?></p>
                <?php get_search_form(); ?>
            </div>
        <?php endif; ?>
    </div>
</main>

<?php
get_sidebar();
get_footer();
`;
  }

  buildFooterPhp(): string {
    return `    <footer id="colophon" class="site-footer">
        <div class="container">
            <div class="footer-widgets">
                <?php
                for ($i = 1; $i <= 4; $i++) {
                    if (is_active_sidebar("footer-{$i}")) {
                        dynamic_sidebar("footer-{$i}");
                    }
                }
                ?>
            </div>

            <div class="footer-bottom">
                <p>&copy; <?php echo date('Y'); ?> <?php bloginfo('name'); ?>.
                    <?php esc_html_e('All rights reserved.', '${this.options.themeSlug}'); ?>
                </p>
            </div>
        </div>
    </footer>
</div>

<?php wp_footer(); ?>
</body>
</html>
`;
  }

  buildThemeJs(): string {
    return `/**
 * ${this.options.themeName} - Theme JavaScript
 */

document.addEventListener('DOMContentLoaded', function () {
    // Mobile menu toggle
    const toggle = document.querySelector('.mobile-menu-toggle');
    const nav = document.querySelector('.main-nav');

    if (toggle && nav) {
        toggle.addEventListener('click', function () {
            nav.classList.toggle('nav--open');
            toggle.classList.toggle('is-active');
        });
    }

    // Header scroll effect
    const header = document.querySelector('.site-header');
    if (header && header.classList.contains('header--sticky')) {
        let lastScroll = 0;

        window.addEventListener('scroll', function () {
            const currentScroll = window.pageYOffset;

            if (currentScroll > lastScroll && currentScroll > 100) {
                header.style.transform = 'translateY(-100%)';
            } else {
                header.style.transform = 'translateY(0)';
            }

            lastScroll = currentScroll;
        });
    }
});
`;
  }

  buildCustomizerPhp(): string {
    return `<?php
/**
 * Customizer Settings for ${this.options.themeName}
 *
 * @package ${this.options.themeSlug}
 */

add_action('customize_register', function ($wp_customize) {
    // === Colors Section ===
    $wp_customize->add_section('${this.options.themeSlug}_colors', [
        'title'    => esc_html__('Theme Colors', '${this.options.themeSlug}'),
        'priority' => 30,
    ]);

    $colors = [
        'primary_color'   => ['label' => 'Primary Color', 'default' => '${this.analysis.designTokens.colors.primary['500'] ?? '#3b82f6'}'],
        'secondary_color' => ['label' => 'Secondary Color', 'default' => '${this.analysis.designTokens.colors.secondary['500'] ?? '#8b5cf6'}'],
        'accent_color'    => ['label' => 'Accent Color', 'default' => '${this.analysis.designTokens.colors.accent['500'] ?? '#f59e0b'}'],
        'body_bg'         => ['label' => 'Background Color', 'default' => '${this.analysis.designTokens.colors.background.body ?? '#ffffff'}'],
        'text_color'      => ['label' => 'Text Color', 'default' => '${this.analysis.designTokens.colors.text.primary ?? '#171717'}'],
    ];

    foreach ($colors as $setting_key => $color) {
        $wp_customize->add_setting($setting_key, [
            'default'           => $color['default'],
            'sanitize_callback' => 'sanitize_hex_color',
        ]);

        $wp_customize->add_control(new WP_Customize_Color_Control(
            $wp_customize,
            $setting_key,
            [
                'label'   => esc_html__($color['label'], '${this.options.themeSlug}'),
                'section' => '${this.options.themeSlug}_colors',
            ]
        ));
    }

    // === Typography Section ===
    $wp_customize->add_section('${this.options.themeSlug}_typography', [
        'title'    => esc_html__('Typography', '${this.options.themeSlug}'),
        'priority' => 35,
    ]);

    $wp_customize->add_setting('heading_font', [
        'default'           => '${this.analysis.designTokens.typography.fontFamilies.heading.name ?? 'Inter'}',
        'sanitize_callback' => 'sanitize_text_field',
    ]);

    $wp_customize->add_control('heading_font', [
        'label'   => esc_html__('Heading Font', '${this.options.themeSlug}'),
        'section' => '${this.options.themeSlug}_typography',
        'type'    => 'select',
        'choices' => [
            'Inter'     => 'Inter',
            'Roboto'    => 'Roboto',
            'Open Sans' => 'Open Sans',
            'Lato'      => 'Lato',
            'Montserrat' => 'Montserrat',
            'Poppins'   => 'Poppins',
            'Playfair Display' => 'Playfair Display',
            'Nunito'    => 'Nunito',
            'Raleway'   => 'Raleway',
        ],
    ]);

    $wp_customize->add_setting('body_font', [
        'default'           => '${this.analysis.designTokens.typography.fontFamilies.body.name ?? 'Inter'}',
        'sanitize_callback' => 'sanitize_text_field',
    ]);

    $wp_customize->add_control('body_font', [
        'label'   => esc_html__('Body Font', '${this.options.themeSlug}'),
        'section' => '${this.options.themeSlug}_typography',
        'type'    => 'select',
        'choices' => [
            'Inter'     => 'Inter',
            'Roboto'    => 'Roboto',
            'Open Sans' => 'Open Sans',
            'Lato'      => 'Lato',
            'Montserrat' => 'Montserrat',
            'Poppins'   => 'Poppins',
            'Nunito'    => 'Nunito',
            'Raleway'   => 'Raleway',
        ],
    ]);

    $wp_customize->add_setting('base_font_size', [
        'default'           => 16,
        'sanitize_callback' => 'absint',
    ]);

    $wp_customize->add_control('base_font_size', [
        'label'       => esc_html__('Base Font Size (px)', '${this.options.themeSlug}'),
        'section'     => '${this.options.themeSlug}_typography',
        'type'        => 'number',
        'input_attrs' => ['min' => 12, 'max' => 24, 'step' => 1],
    ]);

    // === Layout Section ===
    $wp_customize->add_section('${this.options.themeSlug}_layout', [
        'title'    => esc_html__('Layout', '${this.options.themeSlug}'),
        'priority' => 36,
    ]);

    $wp_customize->add_setting('container_width', [
        'default'           => 1140,
        'sanitize_callback' => 'absint',
    ]);

    $wp_customize->add_control('container_width', [
        'label'       => esc_html__('Container Width (px)', '${this.options.themeSlug}'),
        'section'     => '${this.options.themeSlug}_layout',
        'type'        => 'number',
        'input_attrs' => ['min' => 960, 'max' => 1920, 'step' => 10],
    ]);

    $wp_customize->add_setting('header_layout', [
        'default' => 'default',
    ]);

    $wp_customize->add_control('header_layout', [
        'label'   => esc_html__('Header Style', '${this.options.themeSlug}'),
        'section' => '${this.options.themeSlug}_layout',
        'type'    => 'select',
        'choices' => [
            'default' => esc_html__('Default', '${this.options.themeSlug}'),
            'sticky'  => esc_html__('Sticky', '${this.options.themeSlug}'),
            'transparent' => esc_html__('Transparent', '${this.options.themeSlug}'),
        ],
    ]);

    $wp_customize->add_setting('sidebar_position', [
        'default' => 'right',
    ]);

    $wp_customize->add_control('sidebar_position', [
        'label'   => esc_html__('Sidebar Position', '${this.options.themeSlug}'),
        'section' => '${this.options.themeSlug}_layout',
        'type'    => 'select',
        'choices' => [
            'right' => esc_html__('Right', '${this.options.themeSlug}'),
            'left'  => esc_html__('Left', '${this.options.themeSlug}'),
            'none'  => esc_html__('No Sidebar', '${this.options.themeSlug}'),
        ],
    ]);

    $wp_customize->add_setting('blog_layout', [
        'default' => 'grid',
    ]);

    $wp_customize->add_control('blog_layout', [
        'label'   => esc_html__('Blog Layout', '${this.options.themeSlug}'),
        'section' => '${this.options.themeSlug}_layout',
        'type'    => 'select',
        'choices' => [
            'grid'  => esc_html__('Grid', '${this.options.themeSlug}'),
            'list'  => esc_html__('List', '${this.options.themeSlug}'),
            'classic' => esc_html__('Classic', '${this.options.themeSlug}'),
        ],
    ]);

    ${this.analysis.projectType.type === 'ecommerce' ? `
    // === WooCommerce Shop Layout ===
    if (class_exists('WooCommerce')) {
        $wp_customize->add_section('${this.options.themeSlug}_shop', [
            'title'    => esc_html__('Shop Layout', '${this.options.themeSlug}'),
            'priority' => 40,
        ]);

        $wp_customize->add_setting('${this.options.themeSlug}_products_per_row', [
            'default'           => 4,
            'sanitize_callback' => 'absint',
        ]);

        $wp_customize->add_control('${this.options.themeSlug}_products_per_row', [
            'label'       => esc_html__('Products per row', '${this.options.themeSlug}'),
            'section'     => '${this.options.themeSlug}_shop',
            'type'        => 'number',
            'input_attrs' => ['min' => 2, 'max' => 6],
        ]);

        $wp_customize->add_setting('${this.options.themeSlug}_products_per_page', [
            'default'           => 12,
            'sanitize_callback' => 'absint',
        ]);

        $wp_customize->add_control('${this.options.themeSlug}_products_per_page', [
            'label'       => esc_html__('Products per page', '${this.options.themeSlug}'),
            'section'     => '${this.options.themeSlug}_shop',
            'type'        => 'number',
            'input_attrs' => ['min' => 3, 'max' => 60],
        ]);

        $wp_customize->add_setting('${this.options.themeSlug}_catalog_mode', [
            'default' => 'grid',
        ]);

        $wp_customize->add_control('${this.options.themeSlug}_catalog_mode', [
            'label'   => esc_html__('Catalog Display', '${this.options.themeSlug}'),
            'section' => '${this.options.themeSlug}_shop',
            'type'    => 'select',
            'choices' => [
                'grid' => esc_html__('Grid', '${this.options.themeSlug}'),
                'list' => esc_html__('List', '${this.options.themeSlug}'),
            ],
        ]);

        $wp_customize->add_setting('${this.options.themeSlug}_show_quick_view', [
            'default' => false,
        ]);

        $wp_customize->add_control('${this.options.themeSlug}_show_quick_view', [
            'label'   => esc_html__('Enable Quick View', '${this.options.themeSlug}'),
            'section' => '${this.options.themeSlug}_shop',
            'type'    => 'checkbox',
        ]);
    }
    ` : ''}

    // === Social Links Section ===
    $wp_customize->add_section('${this.options.themeSlug}_social', [
        'title'       => esc_html__('Social Links', '${this.options.themeSlug}'),
        'priority'    => 45,
        'description' => esc_html__('Enter full URLs including https://', '${this.options.themeSlug}'),
    ]);

    $social_links = ['facebook', 'twitter', 'instagram', 'linkedin', 'youtube', 'github'];
    foreach ($social_links as $social) {
        $wp_customize->add_setting('${this.options.themeSlug}_social_' . $social, [
            'default'           => '',
            'sanitize_callback' => 'esc_url_raw',
        ]);

        $wp_customize->add_control('${this.options.themeSlug}_social_' . $social, [
            'label'   => ucfirst($social),
            'section' => '${this.options.themeSlug}_social',
            'type'    => 'url',
        ]);
    }
});
`;
  }

  buildWooArchivePhp(): string {
    return `<?php
/**
 * WooCommerce Archive Product Template
 *
 * @package ${this.options.themeSlug}
 */

get_header('shop');
?>

<main id="primary" class="site-main">
    <div class="container">
        <?php
        /**
         * Hook: woocommerce_before_main_content
         */
        do_action('woocommerce_before_main_content');
        ?>

        <header class="woocommerce-products-header">
            <?php if (apply_filters('woocommerce_show_page_title', true)) : ?>
                <h1 class="woocommerce-products-header__title page-title">
                    <?php woocommerce_page_title(); ?>
                </h1>
            <?php endif; ?>

            <?php
            /**
             * Hook: woocommerce_archive_description
             */
            do_action('woocommerce_archive_description');
            ?>
        </header>

        <?php
        if (woocommerce_product_loop()) {
            /**
             * Hook: woocommerce_before_shop_loop
             */
            do_action('woocommerce_before_shop_loop');

            woocommerce_product_loop_start();

            if (wc_get_loop_prop('total')) {
                while (have_posts()) {
                    the_post();
                    /**
                     * Hook: woocommerce_shop_loop
                     */
                    do_action('woocommerce_shop_loop');

                    wc_get_template_part('content', 'product');
                }
            }

            woocommerce_product_loop_end();

            /**
             * Hook: woocommerce_after_shop_loop
             */
            do_action('woocommerce_after_shop_loop');
        } else {
            /**
             * Hook: woocommerce_no_products_found
             */
            do_action('woocommerce_no_products_found');
        }

        /**
         * Hook: woocommerce_after_main_content
         */
        do_action('woocommerce_after_main_content');
        ?>
    </div>
</main>

<?php
get_footer('shop');
`;
  }

  buildWooSinglePhp(): string {
    return `<?php
/**
 * WooCommerce Single Product Template
 *
 * @package ${this.options.themeSlug}
 */

get_header('shop');
?>

<main id="primary" class="site-main">
    <div class="container">
        <?php
        /**
         * Hook: woocommerce_before_main_content
         */
        do_action('woocommerce_before_main_content');
        ?>

        <?php
        while (have_posts()) :
            the_post();

            wc_get_template_part('content', 'single-product');
        endwhile;
        ?>

        <?php
        /**
         * Hook: woocommerce_after_main_content
         */
        do_action('woocommerce_after_main_content');
        ?>
    </div>
</main>

<?php
get_footer('shop');
`;
  }

  buildWooContentProductPhp(): string {
    return `<?php
/**
 * WooCommerce Content Product (Product Card)
 *
 * @package ${this.options.themeSlug}
 */

defined('ABSPATH') || exit;

global $product;
?>
<li <?php wc_product_class('product-card', $product); ?>>
    <?php do_action('woocommerce_before_shop_loop_item'); ?>

    <div class="product-card__image-wrapper">
        <?php
        if ($product->is_on_sale()) {
            echo '<span class="product-card__badge product-card__badge--sale">'
                . esc_html__('Sale!', '${this.options.themeSlug}')
                . '</span>';
        }
        ?>

        <a href="<?php the_permalink(); ?>" class="product-card__link">
            <?php woocommerce_template_loop_product_thumbnail(); ?>
        </a>

        <div class="product-card__actions">
            <?php
            if (shortcode_exists('yith_wcwl_add_to_wishlist')) {
                echo do_shortcode('[yith_wcwl_add_to_wishlist]');
            }
            ?>
        </div>
    </div>

    <div class="product-card__content">
        <?php woocommerce_template_loop_rating(); ?>

        <h3 class="product-card__title">
            <a href="<?php the_permalink(); ?>"><?php the_title(); ?></a>
        </h3>

        <?php if ($post->post_excerpt) : ?>
            <p class="product-card__excerpt"><?php echo wp_trim_words(get_the_excerpt(), 15); ?></p>
        <?php endif; ?>

        <div class="product-card__footer">
            <div class="product-card__price">
                <?php woocommerce_template_loop_price(); ?>
            </div>

            <?php woocommerce_template_loop_add_to_cart(); ?>
        </div>
    </div>

    <?php do_action('woocommerce_after_shop_loop_item'); ?>
</li>`;
  }

  buildWooCartPhp(): string {
    return `<?php
/**
 * WooCommerce Cart Template
 *
 * @package ${this.options.themeSlug}
 */

get_header('shop');
?>
<main id="primary" class="site-main">
  <div class="container">
    <?php
    do_action('woocommerce_before_main_content');

    while (have_posts()) : the_post();
      wc_get_template_part('content', 'page');
    endwhile;

    do_action('woocommerce_after_main_content');
    ?>
  </div>
</main>
<?php
get_footer('shop');
`;
  }

  buildWooCheckoutPhp(): string {
    return `<?php
/**
 * WooCommerce Checkout Template
 *
 * @package ${this.options.themeSlug}
 */

get_header('shop');
?>
<main id="primary" class="site-main">
  <div class="container">
    <?php
    do_action('woocommerce_before_main_content');

    while (have_posts()) : the_post();
      wc_get_template_part('content', 'page');
    endwhile;

    do_action('woocommerce_after_main_content');
    ?>
  </div>
</main>
<?php
get_footer('shop');
`;
  }

  buildWooMyAccountPhp(): string {
    return `<?php
/**
 * WooCommerce My Account Template
 *
 * @package ${this.options.themeSlug}
 */

get_header('shop');
?>
<main id="primary" class="site-main">
  <div class="container">
    <?php
    do_action('woocommerce_before_main_content');

    while (have_posts()) : the_post();
      wc_get_template_part('content', 'page');
    endwhile;

    do_action('woocommerce_after_main_content');
    ?>
  </div>
</main>
<?php
get_footer('shop');
`;
  }

  buildWooCss(): string {
    return `/* ============================================
   WooCommerce Overrides — Generated
   ============================================ */

/* Product Grid */
.products {
  display: grid;
  grid-template-columns: repeat(var(--products-per-row, 4), 1fr);
  gap: var(--spacing-6);
  list-style: none;
  padding: 0;
  margin: 0;
}

/* Product Card (WooCommerce loop) */
.product-card {
  background: var(--color-background-surface);
  border: var(--border-width-default) solid var(--color-border-default);
  border-radius: var(--radius-lg);
  box-shadow: var(--shadow-card);
  overflow: hidden;
  transition: var(--transition-base);
  display: flex;
  flex-direction: column;
  position: relative;
}

.product-card:hover {
  box-shadow: var(--shadow-card-hover);
  transform: translateY(-4px);
}

.product-card__image-wrapper {
  position: relative;
  overflow: hidden;
  aspect-ratio: 1 / 1;
  background: var(--color-neutral-100);
}

.product-card__image-wrapper img {
  width: 100%;
  height: 100%;
  object-fit: cover;
  transition: transform var(--transition-slow);
}

.product-card:hover .product-card__image-wrapper img {
  transform: scale(1.05);
}

.product-card__badge {
  position: absolute;
  top: var(--spacing-3);
  right: var(--spacing-3);
  padding: var(--spacing-1) var(--spacing-2);
  border-radius: var(--radius-sm);
  font-size: var(--text-xs);
  font-weight: var(--font-weight-semibold);
  text-transform: uppercase;
  z-index: 2;
}

.product-card__badge--sale {
  background: var(--color-sale, #ef4444);
  color: white;
}

.product-card__actions {
  position: absolute;
  top: var(--spacing-3);
  left: var(--spacing-3);
  display: flex;
  flex-direction: column;
  gap: var(--spacing-2);
  opacity: 0;
  transform: translateX(-10px);
  transition: var(--transition-base);
  z-index: 2;
}

.product-card:hover .product-card__actions {
  opacity: 1;
  transform: translateX(0);
}

.product-card__content {
  padding: var(--spacing-4);
  display: flex;
  flex-direction: column;
  gap: var(--spacing-2);
  flex: 1;
}

.product-card__title {
  font-size: var(--text-lg);
  font-weight: var(--font-weight-semibold);
  line-height: var(--leading-tight);
  margin: 0;
}

.product-card__title a {
  color: var(--color-text-primary);
  text-decoration: none;
}

.product-card__title a:hover {
  color: var(--color-primary-500);
}

.product-card__excerpt {
  font-size: var(--text-sm);
  color: var(--color-text-secondary);
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
}

.product-card__footer {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-top: auto;
  padding-top: var(--spacing-3);
  border-top: var(--border-width-default) solid var(--color-border-default);
}

.product-card__price {
  display: flex;
  align-items: center;
  gap: var(--spacing-2);
}

.product-card__price .amount {
  font-size: var(--text-xl);
  font-weight: var(--font-weight-bold);
  color: var(--color-text-primary);
}

.product-card__price del .amount {
  font-size: var(--text-base);
  color: var(--color-text-secondary);
}

.product-card__price ins {
  text-decoration: none;
}

.product-card__price ins .amount {
  color: var(--color-ecommerce-sale-price, #ef4444);
}

.product-card__footer .add_to_cart_button {
  display: inline-flex;
  align-items: center;
  gap: var(--spacing-2);
  padding: var(--spacing-2) var(--spacing-4);
  background: var(--color-primary-500);
  color: white;
  border: none;
  border-radius: var(--radius-default);
  font-weight: var(--font-weight-semibold);
  font-size: var(--text-sm);
  cursor: pointer;
  transition: var(--transition-base);
  text-decoration: none;
}

.product-card__footer .add_to_cart_button:hover {
  background: var(--color-primary-600);
}

.product-card__footer .added_to_cart {
  display: none;
}

/* Single Product */
.single-product .site-main > .container {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: var(--spacing-12);
  padding-top: var(--spacing-8);
  padding-bottom: var(--spacing-8);
}

.single-product .woocommerce-product-gallery {
  position: sticky;
  top: var(--spacing-8);
}

.single-product .woocommerce-product-gallery__image {
  border-radius: var(--radius-lg);
  overflow: hidden;
}

.single-product .flex-control-thumbs {
  display: flex;
  gap: var(--spacing-2);
  margin-top: var(--spacing-4);
  list-style: none;
  padding: 0;
}

.single-product .flex-control-thumbs li {
  width: 80px;
  flex: none;
}

.single-product .flex-control-thumbs li img {
  border: 2px solid transparent;
  border-radius: var(--radius-default);
  cursor: pointer;
  transition: var(--transition-base);
}

.single-product .flex-control-thumbs li img.flex-active,
.single-product .flex-control-thumbs li img:hover {
  border-color: var(--color-primary-500);
}

.product_title {
  font-size: var(--text-4xl);
  font-weight: var(--font-weight-bold);
  line-height: var(--leading-tight);
  margin-bottom: var(--spacing-4);
}

.single-product .price {
  display: flex;
  align-items: baseline;
  gap: var(--spacing-3);
  font-size: var(--text-3xl);
  font-weight: var(--font-weight-bold);
  margin-bottom: var(--spacing-4);
}

.single-product .price del {
  color: var(--color-text-secondary);
  font-size: var(--text-xl);
}

.single-product .price ins {
  text-decoration: none;
  color: var(--color-ecommerce-sale-price, #ef4444);
}

.woocommerce-product-rating {
  display: flex;
  align-items: center;
  gap: var(--spacing-2);
  margin-bottom: var(--spacing-4);
}

.star-rating {
  color: var(--color-ecommerce-rating, #f59e0b);
}

.woocommerce-product-details__short-description {
  color: var(--color-text-secondary);
  line-height: var(--leading-relaxed);
  margin-bottom: var(--spacing-6);
}

.cart {
  display: flex;
  flex-direction: column;
  gap: var(--spacing-4);
  padding: var(--spacing-6);
  background: var(--color-background-surface);
  border: var(--border-width-default) solid var(--color-border-default);
  border-radius: var(--radius-lg);
}

.quantity {
  display: flex;
  align-items: center;
  gap: var(--spacing-2);
}

.quantity .qty {
  width: 80px;
  height: 44px;
  padding: var(--spacing-2);
  border: var(--border-width-default) solid var(--color-border-default);
  border-radius: var(--radius-default);
  text-align: center;
  font-size: var(--text-base);
}

.single_add_to_cart_button {
  padding: var(--spacing-4) var(--spacing-8);
  background: var(--color-primary-500);
  color: white;
  border: none;
  border-radius: var(--radius-default);
  font-size: var(--text-base);
  font-weight: var(--font-weight-semibold);
  cursor: pointer;
  transition: var(--transition-base);
}

.single_add_to_cart_button:hover {
  background: var(--color-primary-600);
}

/* WooCommerce Tabs */
.woocommerce-tabs {
  margin-top: var(--spacing-12);
}

.woocommerce-tabs .tabs {
  display: flex;
  gap: var(--spacing-2);
  border-bottom: 2px solid var(--color-border-default);
  margin: 0 0 var(--spacing-6);
  padding: 0;
  list-style: none;
}

.woocommerce-tabs .tabs li {
  margin: 0;
}

.woocommerce-tabs .tabs li a {
  display: block;
  padding: var(--spacing-3) var(--spacing-6);
  font-weight: var(--font-weight-semibold);
  color: var(--color-text-secondary);
  border-bottom: 2px solid transparent;
  margin-bottom: -2px;
  text-decoration: none;
  transition: var(--transition-base);
}

.woocommerce-tabs .tabs li.active a,
.woocommerce-tabs .tabs li a:hover {
  color: var(--color-primary-500);
  border-bottom-color: var(--color-primary-500);
}

.woocommerce-tabs .panel {
  padding: var(--spacing-6) 0;
}

/* Responsive */
@media (max-width: 768px) {
  .products {
    grid-template-columns: repeat(2, 1fr);
  }

  .single-product .site-main > .container {
    grid-template-columns: 1fr;
  }
}

@media (max-width: 480px) {
  .products {
    grid-template-columns: 1fr;
  }
}
`;
  }

  buildElementorWidgetsPhp(): string {
    return `<?php
/**
 * Custom Elementor Widgets for ${this.options.themeName}
 *
 * @package ${this.options.themeSlug}
 */

if (!defined('ABSPATH')) exit;

/**
 * Register Custom Elementor Widgets
 */
add_action('elementor/widgets/register', function ($widgets_manager) {
    // Only register if Elementor is active
    if (!class_exists('\\\\Elementor\\\\Widget_Base')) return;

    class ${this.options.themeSlug}_Product_Card extends \\\\Elementor\\\\Widget_Base {
        public function get_name() {
            return '${this.options.themeSlug}_product_card';
        }

        public function get_title() {
            return esc_html__('Product Card', '${this.options.themeSlug}');
        }

        public function get_icon() {
            return 'eicon-product-image';
        }

        public function get_categories() {
            return ['${this.options.themeSlug}'];
        }

        protected function register_controls() {
            $this->start_controls_section('content_section', [
                'label' => esc_html__('Product Settings', '${this.options.themeSlug}'),
                'tab' => \\\\Elementor\\\\Controls_Manager::TAB_CONTENT,
            ]);

            $this->add_control('product_id', [
                'label' => esc_html__('Product ID', '${this.options.themeSlug}'),
                'type' => \\\\Elementor\\\\Controls_Manager::NUMBER,
                'placeholder' => 'Auto (current)',
            ]);

            $this->add_control('show_rating', [
                'label' => esc_html__('Show Rating', '${this.options.themeSlug}'),
                'type' => \\\\Elementor\\\\Controls_Manager::SWITCHER,
                'default' => 'yes',
            ]);

            $this->add_control('show_excerpt', [
                'label' => esc_html__('Show Excerpt', '${this.options.themeSlug}'),
                'type' => \\\\Elementor\\\\Controls_Manager::SWITCHER,
                'default' => 'yes',
            ]);

            $this->end_controls_section();
        }

        protected function render() {
            $settings = $this->get_settings_for_display();
            $product_id = $settings['product_id'] ? intval($settings['product_id']) : get_the_ID();
            $product = wc_get_product($product_id);

            if (!$product) {
                echo '<p>' . esc_html__('Product not found.', '${this.options.themeSlug}') . '</p>';
                return;
            }

            ?>
            <article class="product-card">
                <div class="product-card__image-wrapper">
                    <?php if ($product->is_on_sale()) : ?>
                        <span class="product-card__badge product-card__badge--sale">
                            <?php esc_html_e('Sale!', '${this.options.themeSlug}'); ?>
                        </span>
                    <?php endif; ?>

                    <a href="<?php echo esc_url(get_permalink($product_id)); ?>">
                        <?php echo $product->get_image('woocommerce_thumbnail'); ?>
                    </a>
                </div>

                <div class="product-card__content">
                    <?php if ('yes' === $settings['show_rating']) : ?>
                        <?php echo wc_get_rating_html($product->get_average_rating()); ?>
                    <?php endif; ?>

                    <h3 class="product-card__title">
                        <a href="<?php echo esc_url(get_permalink($product_id)); ?>">
                            <?php echo esc_html($product->get_name()); ?>
                        </a>
                    </h3>

                    <?php if ('yes' === $settings['show_excerpt'] && $product->get_short_description()) : ?>
                        <p class="product-card__excerpt">
                            <?php echo esc_html(wp_trim_words($product->get_short_description(), 15)); ?>
                        </p>
                    <?php endif; ?>

                    <div class="product-card__footer">
                        <div class="product-card__price">
                            <?php echo $product->get_price_html(); ?>
                        </div>
                        <?php woocommerce_template_loop_add_to_cart(['product_id' => $product_id]); ?>
                    </div>
                </div>
            </article>
            <?php
        }
    }

    $widgets_manager->register(new ${this.options.themeSlug}_Product_Card());
});

/**
 * Register Elementor Category
 */
add_action('elementor/elements/categories_registered', function ($elements_manager) {
    $elements_manager->add_category('${this.options.themeSlug}', [
        'title' => esc_html__('${this.options.themeName}', '${this.options.themeSlug}'),
        'icon' => 'fa fa-plug',
    ]);
});
`;
  }

  buildElementorJson(template: ElementorTemplate): string {
    return JSON.stringify(template, null, 2);
  }

  buildGlobalSettingsJson(settings: GlobalSettings): string {
    return JSON.stringify(settings, null, 2);
  }

  buildThemeJson(): string {
    const generator = new ThemeJsonGenerator(this.analysis.designTokens);
    return generator.toJSON();
  }

  buildBlockPatterns(): { path: string; content: string }[] {
    const generator = new WpBlockGenerator(this.analysis.components, this.analysis.designTokens);
    return generator.generatePatterns().map((pattern) => ({
      path: `patterns/${pattern.slug}.php`,
      content: this.buildPatternPhp(pattern),
    }));
  }

  private buildBlockPatternsFromCodeGen(patterns: BlockPattern[]): { path: string; content: string }[] {
    return patterns.map((pattern) => ({
      path: `patterns/${pattern.slug}.php`,
      content: this.buildPatternPhp(pattern),
    }));
  }

  private buildPatternPhp(pattern: { title: string; slug: string; description?: string; categories: string[]; content: string; viewportWidth?: number; inserter?: boolean }): string {
    const header = [
      '<?php',
      '/**',
      ` * Title: ${pattern.title}`,
      ` * Slug: ${this.options.themeSlug}/${pattern.slug}`,
      pattern.description ? ` * Description: ${pattern.description}` : null,
      ` * Categories: ${pattern.categories.join(', ')}`,
      pattern.viewportWidth ? ` * Viewport Width: ${pattern.viewportWidth}` : null,
      pattern.inserter === false ? ' * Inserter: no' : null,
      ' */',
      '?>',
    ].filter((line): line is string => line !== null).join('\n');

    return `${header}\n${pattern.content}\n`;
  }

  buildBlockTemplates(): { path: string; content: string }[] {
    const generator = new WpBlockGenerator(this.analysis.components, this.analysis.designTokens);
    return generator.generateTemplates().map((template) => ({
      path: `templates/${template.slug}.html`,
      content: template.content,
    }));
  }

  buildScreenshotPng(): Buffer {
    const width = 880;
    const height = 660;
    const primary = this.analysis.designTokens.colors.primary['500'] ?? '#3b82f6';
    const bg = this.analysis.designTokens.colors.neutral['50'] ?? '#fafafa';

    const r = (hex: string) => parseInt(hex.slice(1, 3), 16);
    const g = (hex: string) => parseInt(hex.slice(3, 5), 16);
    const b = (hex: string) => parseInt(hex.slice(5, 7), 16);

    const bgR = r(bg), bgG = g(bg), bgB = b(bg);
    const prR = r(primary), prG = g(primary), prB = b(primary);

    const raw = Buffer.alloc(height * width * 4);
    const headerHeight = 80;
    const footerHeight = 60;
    const sidebarW = 260;

    for (let y = 0; y < height; y++) {
      for (let x = 0; x < width; x++) {
        const idx = (y * width + x) * 4;
        let cr = bgR, cg = bgG, cb = bgB, ca = 255;

        if (y < headerHeight) {
          cr = prR; cg = prG; cb = prB;
        } else if (y >= height - footerHeight) {
          cr = Math.round(prR * 0.85 + bgR * 0.15);
          cg = Math.round(prG * 0.85 + bgG * 0.15);
          cb = Math.round(prB * 0.85 + bgB * 0.15);
        } else if (x < sidebarW) {
          cr = Math.round(bgR * 0.97); cg = Math.round(bgG * 0.97); cb = Math.round(bgB * 0.97);
        }

        raw[idx] = cr;
        raw[idx + 1] = cg;
        raw[idx + 2] = cb;
        raw[idx + 3] = ca;
      }
    }

    const wB = Buffer.alloc(4); wB.writeUInt32BE(width);
    const hB = Buffer.alloc(4); hB.writeUInt32BE(height);

    const rawData = Buffer.concat([
      Buffer.from([0x49, 0x48, 0x44, 0x52]), wB, hB,
      Buffer.from([8, 6, 0, 0, 0]),
      crc32(Buffer.concat([Buffer.from([0x49, 0x48, 0x44, 0x52]), wB, hB, Buffer.from([8, 6, 0, 0, 0])])),
    ]);

    const scanlines: Buffer[] = [];
    const filterNone = Buffer.from([0]);
    for (let y = 0; y < height; y++) {
      const row = raw.subarray(y * width * 4, (y + 1) * width * 4);
      scanlines.push(Buffer.concat([filterNone, row]));
    }

    const rawRows = Buffer.concat(scanlines);
    const deflated = zlib.deflateSync(rawRows);
    const idatData = Buffer.concat([
      Buffer.from([0x49, 0x44, 0x41, 0x54]),
      deflated,
      crc32(Buffer.concat([Buffer.from([0x49, 0x44, 0x41, 0x54]), deflated])),
    ]);

    const ihdrLen = Buffer.alloc(4); ihdrLen.writeUInt32BE(13);
    const idatLen = Buffer.alloc(4); idatLen.writeUInt32BE(deflated.length + 4 + 4);

    const iend = Buffer.concat([
      Buffer.from([0x00, 0x00, 0x00, 0x00, 0x49, 0x45, 0x4E, 0x44]),
      crc32(Buffer.from([0x49, 0x45, 0x4E, 0x44])),
    ]);

    const signature = Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]);

    return Buffer.concat([signature, ihdrLen, rawData, idatLen, idatData, iend]);

    function crc32(buf: Buffer): Buffer {
      const table = new Int32Array(256);
      for (let n = 0; n < 256; n++) {
        let c = n;
        for (let k = 0; k < 8; k++) {
          c = (c & 1) ? (0xEDB88320 ^ (c >>> 1)) : (c >>> 1);
        }
        table[n] = c;
      }
      let crc = 0xFFFFFFFF;
      for (let i = 0; i < buf.length; i++) {
        crc = table[(crc ^ buf[i]) & 0xFF] ^ (crc >>> 8);
      }
      const result = Buffer.alloc(4);
      result.writeUInt32BE((crc ^ 0xFFFFFFFF) >>> 0);
      return result;
    }
  }

  buildRobotsTxt(): string {
    return `User-agent: *
Allow: /

# Disallow sensitive paths
Disallow: /wp-admin/
Disallow: /wp-includes/
Disallow: /wp-content/plugins/
Disallow: /wp-content/themes/${this.options.themeSlug}/inc/
`;
  }

  buildReadmeTxt(): string {
    const slug = this.options.themeSlug;
    const name = this.options.themeName;
    const isEcom = this.analysis.projectType.type === 'ecommerce';
    return `=== ${name} ===
Contributors: typefigma
Requires at least: 6.0
Tested up to: 6.7
Requires PHP: 8.0
Stable tag: 1.0.0
License: GPLv2 or later
License URI: https://www.gnu.org/licenses/gpl-2.0.html

A WordPress theme generated by TypeFigma from Figma designs.

== Description ==

${name} is a fully responsive WordPress theme generated automatically from Figma designs using TypeFigma. It features modern design, optimized performance, and full compatibility with the WordPress Block Editor and Elementor page builder.

== Features ==

* Responsive design (mobile-first)
* Full Site Editing (FSE) support with theme.json
* Elementor integration with custom widgets
* WooCommerce compatibility${isEcom ? ' with shop, cart, checkout, and my-account templates' : ''}
* Customizer settings for colors, typography, and layout
* Accessibility ready (WCAG AA compliant)
* SEO-friendly semantic HTML5 markup
* Cross-browser compatible
* Translation ready
* Social media links

== Installation ==

1. Upload the \`${slug}\` folder to the \`/wp-content/themes/\` directory.
2. Activate the theme through the 'Appearance > Themes' menu in WordPress.
3. Configure theme settings via Appearance > Customize.
4. (Optional) Import demo content from \`demo-content.xml\` using Tools > Import > WordPress.

== Required Plugins ==

* Elementor (free) - for page building
${isEcom ? '* WooCommerce - for e-commerce functionality\n' : ''}
== Changelog ==

= 1.0.0 =
* Initial release generated by TypeFigma
`;
  }

  buildFontsPhp(fonts: FontFamilyEntry[]): string {
    if (fonts.length === 0) {
      return `<?php\n// No custom fonts configured\n`;
    }

    const slug = this.options.themeSlug;
    const lines: string[] = [
      '<?php',
      '/**',
      ' * Font Enqueue',
      ` * @package ${slug}`,
      ' */',
      '',
      `function ${slug}_enqueue_fonts() {`,
    ];

    for (const entry of fonts) {
      const family = entry.fontFace[0]?.fontFamily || entry.name;
      const weights = [...new Set(entry.fontFace.map(f => f.fontWeight))].filter(w => w !== 'undefined').join(',');
      if (!weights || !family) continue;

      const italic = entry.fontFace.some(f => f.fontStyle === 'italic');
      const encodedFamily = encodeURIComponent(family);
      let fontUrl: string;
      if (italic) {
        const wSplit = weights.split(',');
        fontUrl = `https://fonts.googleapis.com/css2?family=${encodedFamily}:ital,wght@0,${wSplit.join(';0,')};1,${wSplit.join(';1,')}&display=swap`;
      } else {
        fontUrl = `https://fonts.googleapis.com/css2?family=${encodedFamily}:wght@${weights}&display=swap`;
      }

      lines.push(`    wp_enqueue_style( '${slug}-${entry.slug}', '${fontUrl}', array(), null );`);

      const hasLocalFiles = entry.fontFace.some(f => f.src.some(s => s.startsWith('file:')));
      if (hasLocalFiles) {
        lines.push(`    // Local font assets for ${family} should be in assets/fonts/${entry.slug}/`);
      }
    }

    lines.push('}');
    lines.push(`add_action( 'wp_enqueue_scripts', '${slug}_enqueue_fonts' );`);
    return lines.join('\n');
  }

  buildFontFaceCss(fonts: FontFamilyEntry[]): string {
    const lines: string[] = [];
    for (const entry of fonts) {
      for (const face of entry.fontFace) {
        if (face.src.some(s => s.startsWith('file:'))) {
          lines.push('@font-face {');
          lines.push(`  font-family: '${face.fontFamily}';`);
          lines.push(`  font-weight: ${face.fontWeight};`);
          lines.push(`  font-style: ${face.fontStyle};`);
          lines.push(`  font-display: ${face.fontDisplay};`);
          lines.push(`  src: ${face.src.map(s => `url('${s}')`).join(', ')};`);
          lines.push('}');
        }
      }
    }
    return lines.join('\n');
  }

  getAllFiles(
    elementorTemplates: ElementorTemplate[],
    globalSettings: GlobalSettings,
    codeGen: GeneratedCode,
    fontEntries?: FontFamilyEntry[],
  ): ThemeFile[] {
    const files: ThemeFile[] = [
      { path: 'style.css', content: this.buildStyleCss() },
      { path: 'functions.php', content: this.buildFunctionsPhp() },
      { path: 'index.php', content: this.buildIndexPhp() },
      { path: 'single.php', content: this.buildSinglePhp() },
      { path: 'page.php', content: this.buildPagePhp() },
      { path: 'archive.php', content: this.buildArchivePhp() },
      { path: 'sidebar.php', content: this.buildSidebarPhp() },
      { path: '404.php', content: this.build404Php() },
      { path: 'search.php', content: this.buildSearchPhp() },
      { path: 'header.php', content: this.buildHeaderPhp() },
      { path: 'footer.php', content: this.buildFooterPhp() },
      { path: 'assets/css/global.css', content: codeGen.globalCss },
      { path: 'assets/css/components.css', content: codeGen.componentsCss },
      { path: 'assets/js/theme.js', content: this.buildThemeJs() },
      { path: 'inc/customizer.php', content: this.buildCustomizerPhp() },
      { path: 'elementor/global-settings.json', content: this.buildGlobalSettingsJson(globalSettings) },
      { path: 'theme.json', content: codeGen.themeJson || this.buildThemeJson() },
      ...(codeGen.blockPatterns ? this.buildBlockPatternsFromCodeGen(codeGen.blockPatterns) : []),
      ...(codeGen.blockTemplates ? codeGen.blockTemplates.map(t => ({ path: `templates/${t.slug}.html`, content: t.content })) : []),
    ];

    for (const template of elementorTemplates) {
      files.push({
        path: `elementor/templates/${template.type}.json`,
        content: this.buildElementorJson(template),
      });
    }

    if (this.analysis.projectType.type === 'ecommerce') {
      files.push(
        { path: 'woocommerce/archive-product.php', content: this.buildWooArchivePhp() },
        { path: 'woocommerce/single-product.php', content: this.buildWooSinglePhp() },
        { path: 'woocommerce/content-product.php', content: this.buildWooContentProductPhp() },
        { path: 'woocommerce/cart.php', content: this.buildWooCartPhp() },
        { path: 'woocommerce/checkout.php', content: this.buildWooCheckoutPhp() },
        { path: 'woocommerce/myaccount.php', content: this.buildWooMyAccountPhp() },
        { path: 'assets/css/woocommerce.css', content: this.buildWooCss() },
      );
    }

    files.push(
      { path: 'screenshot.png', content: this.buildScreenshotPng() },
      { path: 'inc/elementor-widgets.php', content: this.buildElementorWidgetsPhp() },
      { path: 'demo-content.xml', content: this.buildDemoContentXml() },
      { path: 'readme.txt', content: this.buildReadmeTxt() },
      { path: 'robots.txt', content: this.buildRobotsTxt() },
    );

    if (fontEntries && fontEntries.length > 0) {
      files.push(
        { path: 'inc/fonts.php', content: this.buildFontsPhp(fontEntries) },
      );

      const fontCss = this.buildFontFaceCss(fontEntries);
      if (fontCss) {
        files.push({ path: 'assets/css/fonts.css', content: fontCss });
      }

      for (const entry of fontEntries) {
        for (const face of entry.fontFace) {
          for (const src of face.src) {
            const fileMatch = src.match(/file:\.\/assets\/fonts\/(.+)/);
            if (fileMatch && (entry as any)._fontAssets) {
              const asset = (entry as any)._fontAssets.find((a: { filename: string }) => a.filename === fileMatch[1]);
              if (asset) {
                files.push({ path: `assets/fonts/${entry.slug}/${asset.filename}`, content: asset.file });
              }
            }
          }
        }
      }
    }

    const adminPanel = new AdminPanelGenerator({
      themeSlug: this.options.themeSlug,
      themeName: this.options.themeName,
      tokens: this.analysis.designTokens,
      components: this.analysis.components,
      fonts: fontEntries,
    });

    for (const f of adminPanel.getFileList()) {
      files.push(f);
    }

    return files;
  }

  buildDemoContentXml(): string {
    const siteName = this.options.themeName;
    const isEcom = this.analysis.projectType.type === 'ecommerce';
    const now = new Date().toISOString();

    return `<?xml version="1.0" encoding="UTF-8"?>
<!-- WordPress eXtended RSS (WXR) for ${siteName} -->
<rss version="2.0"
  xmlns:excerpt="http://wordpress.org/export/1.2/excerpt/"
  xmlns:content="http://purl.org/rss/1.0/modules/content/"
  xmlns:dc="http://purl.org/dc/elements/1.1/"
  xmlns:wp="http://wordpress.org/export/1.2/">
<channel>
  <title>${this.xmlEsc(siteName)}</title>
  <link>https://example.com</link>
  <description>${this.xmlEsc(siteName)} — built with TypeFigma</description>
  <language>en-US</language>
  <wp:wxr_version>1.2</wp:wxr_version>

  <wp:author>
    <wp:author_id>1</wp:author_id>
    <wp:author_login>admin</wp:author_login>
    <wp:author_email>admin@example.com</wp:author_email>
    <wp:author_display_name>Admin</wp:author_display_name>
  </wp:author>

  <!-- Categories -->
  <wp:category>
    <wp:term_id>1</wp:term_id>
    <wp:category_nicename>uncategorized</wp:category_nicename>
    <wp:category_parent></wp:category_parent>
    <wp:cat_name><![CDATA[Uncategorized]]></wp:cat_name>
  </wp:category>

  <wp:category>
    <wp:term_id>2</wp:term_id>
    <wp:category_nicename>news</wp:category_nicename>
    <wp:category_parent></wp:category_parent>
    <wp:cat_name><![CDATA[News]]></wp:cat_name>
  </wp:category>
  ${isEcom ? `
  <wp:category>
    <wp:term_id>3</wp:term_id>
    <wp:category_nicename>products</wp:category_nicename>
    <wp:category_parent></wp:category_parent>
    <wp:cat_name><![CDATA[Products]]></wp:cat_name>
  </wp:category>` : ''}

  <!-- Tags -->
  <wp:tag>
    <wp:term_id>1</wp:term_id>
    <wp:tag_slug>featured</wp:tag_slug>
    <wp:tag_name><![CDATA[featured]]></wp:tag_name>
  </wp:tag>
  ${isEcom ? `
  <!-- Product Categories (WooCommerce) -->
  <wp:term>
    <wp:term_id>10</wp:term_id>
    <wp:term_taxonomy>product_cat</wp:term_taxonomy>
    <wp:term_slug>clothing</wp:term_slug>
    <wp:term_parent></wp:term_parent>
    <wp:term_name><![CDATA[Clothing]]></wp:term_name>
  </wp:term>
  <wp:term>
    <wp:term_id>11</wp:term_id>
    <wp:term_taxonomy>product_cat</wp:term_taxonomy>
    <wp:term_slug>accessories</wp:term_slug>
    <wp:term_parent></wp:term_parent>
    <wp:term_name><![CDATA[Accessories]]></wp:term_name>
  </wp:term>
  <wp:term>
    <wp:term_id>12</wp:term_id>
    <wp:term_taxonomy>product_cat</wp:term_taxonomy>
    <wp:term_slug>home-garden</wp:term_slug>
    <wp:term_parent></wp:term_parent>
    <wp:term_name><![CDATA[Home & Garden]]></wp:term_name>
  </wp:term>
  <wp:term>
    <wp:term_id>13</wp:term_id>
    <wp:term_taxonomy>product_tag</wp:term_taxonomy>
    <wp:term_slug>new</wp:term_slug>
    <wp:term_parent></wp:term_parent>
    <wp:term_name><![CDATA[new]]></wp:term_name>
  </wp:term>` : ''}

  <!-- Navigation Menu -->
  <wp:term>
    <wp:term_id>20</wp:term_id>
    <wp:term_taxonomy>nav_menu</wp:term_taxonomy>
    <wp:term_slug>primary</wp:term_slug>
    <wp:term_name><![CDATA[Primary Menu]]></wp:term_name>
  </wp:term>

  <!-- === Pages === -->

  <item>
    <title>Home</title>
    <dc:creator><![CDATA[admin]]></dc:creator>
    <content:encoded><![CDATA[<!-- wp:paragraph -->
<p>Welcome to ${this.xmlEsc(siteName)}. This is your home page.</p>
<!-- /wp:paragraph -->]]></content:encoded>
    <wp:post_id>1</wp:post_id>
    <wp:post_date>${now}</wp:post_date>
    <wp:post_type>page</wp:post_type>
    <wp:status>publish</wp:status>
    <wp:menu_order>0</wp:menu_order>
    <wp:comment_status>closed</wp:comment_status>
    <wp:post_name>home</wp:post_name>
  </item>

  <item>
    <title>About</title>
    <dc:creator><![CDATA[admin]]></dc:creator>
    <content:encoded><![CDATA[<!-- wp:paragraph -->
<p>About ${this.xmlEsc(siteName)}. We build amazing digital experiences.</p>
<!-- /wp:paragraph -->

<!-- wp:heading -->
<h2>Our Mission</h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>To deliver high-quality WordPress solutions powered by design.</p>
<!-- /wp:paragraph -->]]></content:encoded>
    <wp:post_id>2</wp:post_id>
    <wp:post_date>${now}</wp:post_date>
    <wp:post_type>page</wp:post_type>
    <wp:status>publish</wp:status>
    <wp:menu_order>1</wp:menu_order>
    <wp:comment_status>closed</wp:comment_status>
    <wp:post_name>about</wp:post_name>
  </item>

  <item>
    <title>Contact</title>
    <dc:creator><![CDATA[admin]]></dc:creator>
    <content:encoded><![CDATA[<!-- wp:paragraph -->
<p>Get in touch with us. Use the form below or email us at hello@example.com.</p>
<!-- /wp:paragraph -->]]></content:encoded>
    <wp:post_id>3</wp:post_id>
    <wp:post_date>${now}</wp:post_date>
    <wp:post_type>page</wp:post_type>
    <wp:status>publish</wp:status>
    <wp:menu_order>2</wp:menu_order>
    <wp:comment_status>closed</wp:comment_status>
    <wp:post_name>contact</wp:post_name>
  </item>
  ${isEcom ? `
  <!-- === WooCommerce Pages === -->
  <item>
    <title>Shop</title>
    <dc:creator><![CDATA[admin]]></dc:creator>
    <content:encoded><![CDATA[<!-- wp:paragraph -->
<p>Browse our products.</p>
<!-- /wp:paragraph -->]]></content:encoded>
    <wp:post_id>4</wp:post_id>
    <wp:post_date>${now}</wp:post_date>
    <wp:post_type>page</wp:post_type>
    <wp:status>publish</wp:status>
    <wp:menu_order>3</wp:menu_order>
    <wp:comment_status>closed</wp:comment_status>
    <wp:post_name>shop</wp:post_name>
  </item>

  <!-- Sample Products -->
  <item>
    <title>Classic T-Shirt</title>
    <dc:creator><![CDATA[admin]]></dc:creator>
    <content:encoded><![CDATA[Premium quality cotton t-shirt. Comfortable and durable for everyday wear.]]></content:encoded>
    <wp:post_id>10</wp:post_id>
    <wp:post_date>${now}</wp:post_date>
    <wp:post_type>product</wp:post_type>
    <wp:status>publish</wp:status>
    <wp:post_name>classic-t-shirt</wp:post_name>
    <category domain="product_cat" nicename="clothing"><![CDATA[Clothing]]></category>
    <category domain="product_tag" nicename="new"><![CDATA[new]]></category>
    <wp:postmeta>
      <wp:meta_key>_regular_price</wp:meta_key>
      <wp:meta_value><![CDATA[29.99]]></wp:meta_value>
    </wp:postmeta>
    <wp:postmeta>
      <wp:meta_key>_price</wp:meta_key>
      <wp:meta_value><![CDATA[29.99]]></wp:meta_value>
    </wp:postmeta>
    <wp:postmeta>
      <wp:meta_key>_sku</wp:meta_key>
      <wp:meta_value><![CDATA[TSH-001]]></wp:meta_value>
    </wp:postmeta>
    <wp:postmeta>
      <wp:meta_key>_stock_status</wp:meta_key>
      <wp:meta_value><![CDATA[instock]]></wp:meta_value>
    </wp:postmeta>
    <wp:postmeta>
      <wp:meta_key>_weight</wp:meta_key>
      <wp:meta_value><![CDATA[0.3]]></wp:meta_value>
    </wp:postmeta>
    <wp:postmeta>
      <wp:meta_key>_product_image_gallery</wp:meta_key>
      <wp:meta_value><![CDATA[]]></wp:meta_value>
    </wp:postmeta>
  </item>

  <item>
    <title>Leather Wallet</title>
    <dc:creator><![CDATA[admin]]></dc:creator>
    <content:encoded><![CDATA[Handcrafted genuine leather wallet with multiple card slots and RFID protection.]]></content:encoded>
    <wp:post_id>11</wp:post_id>
    <wp:post_date>${now}</wp:post_date>
    <wp:post_type>product</wp:post_type>
    <wp:status>publish</wp:status>
    <wp:post_name>leather-wallet</wp:post_name>
    <category domain="product_cat" nicename="accessories"><![CDATA[Accessories]]></category>
    <wp:postmeta>
      <wp:meta_key>_regular_price</wp:meta_key>
      <wp:meta_value><![CDATA[49.99]]></wp:meta_value>
    </wp:postmeta>
    <wp:postmeta>
      <wp:meta_key>_sale_price</wp:meta_key>
      <wp:meta_value><![CDATA[39.99]]></wp:meta_value>
    </wp:postmeta>
    <wp:postmeta>
      <wp:meta_key>_price</wp:meta_key>
      <wp:meta_value><![CDATA[39.99]]></wp:meta_value>
    </wp:postmeta>
    <wp:postmeta>
      <wp:meta_key>_sku</wp:meta_key>
      <wp:meta_value><![CDATA[WAL-002]]></wp:meta_value>
    </wp:postmeta>
    <wp:postmeta>
      <wp:meta_key>_stock_status</wp:meta_key>
      <wp:meta_value><![CDATA[instock]]></wp:meta_value>
    </wp:postmeta>
  </item>

  <item>
    <title>Potted Plant</title>
    <dc:creator><![CDATA[admin]]></dc:creator>
    <content:encoded><![CDATA[Beautiful indoor ceramic potted plant. Perfect for home or office decoration.]]></content:encoded>
    <wp:post_id>12</wp:post_id>
    <wp:post_date>${now}</wp:post_date>
    <wp:post_type>product</wp:post_type>
    <wp:status>publish</wp:status>
    <wp:post_name>potted-plant</wp:post_name>
    <category domain="product_cat" nicename="home-garden"><![CDATA[Home & Garden]]></category>
    <wp:postmeta>
      <wp:meta_key>_regular_price</wp:meta_key>
      <wp:meta_value><![CDATA[34.99]]></wp:meta_value>
    </wp:postmeta>
    <wp:postmeta>
      <wp:meta_key>_price</wp:meta_key>
      <wp:meta_value><![CDATA[34.99]]></wp:meta_value>
    </wp:postmeta>
    <wp:postmeta>
      <wp:meta_key>_sku</wp:meta_key>
      <wp:meta_value><![CDATA[PLT-003]]></wp:meta_value>
    </wp:postmeta>
    <wp:postmeta>
      <wp:meta_key>_stock_status</wp:meta_key>
      <wp:meta_value><![CDATA[instock]]></wp:meta_value>
    </wp:postmeta>
  </item>
  ` : ''}

  <!-- Blog Post -->
  <item>
    <title>Hello World</title>
    <dc:creator><![CDATA[admin]]></dc:creator>
    <content:encoded><![CDATA[<!-- wp:paragraph -->
<p>Welcome to ${this.xmlEsc(siteName)}. This is your first post. Edit or delete it to start your blog.</p>
<!-- /wp:paragraph -->

<!-- wp:heading -->
<h2>Getting Started</h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Customize your theme in the <a href="/wp-admin/customize.php">Customizer</a> or use Elementor to build pages visually.</p>
<!-- /wp:paragraph -->]]></content:encoded>
    <wp:post_id>20</wp:post_id>
    <wp:post_date>${now}</wp:post_date>
    <wp:post_type>post</wp:post_type>
    <wp:status>publish</wp:status>
    <wp:comment_status>open</wp:comment_status>
    <wp:post_name>hello-world</wp:post_name>
    <category domain="category" nicename="uncategorized"><![CDATA[Uncategorized]]></category>
  </item>

  <!-- Menu Items -->
  <item>
    <title>Home</title>
    <dc:creator><![CDATA[admin]]></dc:creator>
    <wp:post_id>30</wp:post_id>
    <wp:post_date>${now}</wp:post_date>
    <wp:post_type>nav_menu_item</wp:post_type>
    <wp:status>publish</wp:status>
    <wp:post_name></wp:post_name>
    <wp:postmeta>
      <wp:meta_key>_menu_item_type</wp:meta_key>
      <wp:meta_value><![CDATA[post_type]]></wp:meta_value>
    </wp:postmeta>
    <wp:postmeta>
      <wp:meta_key>_menu_item_menu_item_parent</wp:meta_key>
      <wp:meta_value><![CDATA[0]]></wp:meta_value>
    </wp:postmeta>
    <wp:postmeta>
      <wp:meta_key>_menu_item_object_id</wp:meta_key>
      <wp:meta_value><![CDATA[1]]></wp:meta_value>
    </wp:postmeta>
    <wp:postmeta>
      <wp:meta_key>_menu_item_object</wp:meta_key>
      <wp:meta_value><![CDATA[page]]></wp:meta_value>
    </wp:postmeta>
    <wp:postmeta>
      <wp:meta_key>_menu_item_orphaned</wp:meta_key>
      <wp:meta_value><![CDATA[${now}]]></wp:meta_value>
    </wp:postmeta>
    <category domain="nav_menu" nicename="primary"><![CDATA[Primary Menu]]></category>
  </item>

  <item>
    <title>About</title>
    <dc:creator><![CDATA[admin]]></dc:creator>
    <wp:post_id>31</wp:post_id>
    <wp:post_date>${now}</wp:post_date>
    <wp:post_type>nav_menu_item</wp:post_type>
    <wp:status>publish</wp:status>
    <wp:post_name></wp:post_name>
    <wp:postmeta>
      <wp:meta_key>_menu_item_type</wp:meta_key>
      <wp:meta_value><![CDATA[post_type]]></wp:meta_value>
    </wp:postmeta>
    <wp:postmeta>
      <wp:meta_key>_menu_item_menu_item_parent</wp:meta_key>
      <wp:meta_value><![CDATA[0]]></wp:meta_value>
    </wp:postmeta>
    <wp:postmeta>
      <wp:meta_key>_menu_item_object_id</wp:meta_key>
      <wp:meta_value><![CDATA[2]]></wp:meta_value>
    </wp:postmeta>
    <wp:postmeta>
      <wp:meta_key>_menu_item_object</wp:meta_key>
      <wp:meta_value><![CDATA[page]]></wp:meta_value>
    </wp:postmeta>
    <category domain="nav_menu" nicename="primary"><![CDATA[Primary Menu]]></category>
  </item>

  <item>
    <title>Contact</title>
    <dc:creator><![CDATA[admin]]></dc:creator>
    <wp:post_id>32</wp:post_id>
    <wp:post_date>${now}</wp:post_date>
    <wp:post_type>nav_menu_item</wp:post_type>
    <wp:status>publish</wp:status>
    <wp:post_name></wp:post_name>
    <wp:postmeta>
      <wp:meta_key>_menu_item_type</wp:meta_key>
      <wp:meta_value><![CDATA[post_type]]></wp:meta_value>
    </wp:postmeta>
    <wp:postmeta>
      <wp:meta_key>_menu_item_menu_item_parent</wp:meta_key>
      <wp:meta_value><![CDATA[0]]></wp:meta_value>
    </wp:postmeta>
    <wp:postmeta>
      <wp:meta_key>_menu_item_object_id</wp:meta_key>
      <wp:meta_value><![CDATA[3]]></wp:meta_value>
    </wp:postmeta>
    <wp:postmeta>
      <wp:meta_key>_menu_item_object</wp:meta_key>
      <wp:meta_value><![CDATA[page]]></wp:meta_value>
    </wp:postmeta>
    <category domain="nav_menu" nicename="primary"><![CDATA[Primary Menu]]></category>
  </item>
  ${isEcom ? `
  <item>
    <title>Shop</title>
    <dc:creator><![CDATA[admin]]></dc:creator>
    <wp:post_id>33</wp:post_id>
    <wp:post_date>${now}</wp:post_date>
    <wp:post_type>nav_menu_item</wp:post_type>
    <wp:status>publish</wp:status>
    <wp:post_name></wp:post_name>
    <wp:postmeta>
      <wp:meta_key>_menu_item_type</wp:meta_key>
      <wp:meta_value><![CDATA[post_type]]></wp:meta_value>
    </wp:postmeta>
    <wp:postmeta>
      <wp:meta_key>_menu_item_menu_item_parent</wp:meta_key>
      <wp:meta_value><![CDATA[0]]></wp:meta_value>
    </wp:postmeta>
    <wp:postmeta>
      <wp:meta_key>_menu_item_object_id</wp:meta_key>
      <wp:meta_value><![CDATA[4]]></wp:meta_value>
    </wp:postmeta>
    <wp:postmeta>
      <wp:meta_key>_menu_item_object</wp:meta_key>
      <wp:meta_value><![CDATA[page]]></wp:meta_value>
    </wp:postmeta>
    <category domain="nav_menu" nicename="primary"><![CDATA[Primary Menu]]></category>
  </item>
  <!-- Set up WooCommerce pages -->
  <item>
    <title>Cart</title>
    <dc:creator><![CDATA[admin]]></dc:creator>
    <content:encoded><![CDATA[<!-- wp:paragraph --><p>Your cart is empty.</p><!-- /wp:paragraph -->]]></content:encoded>
    <wp:post_id>40</wp:post_id>
    <wp:post_date>${now}</wp:post_date>
    <wp:post_type>page</wp:post_type>
    <wp:status>publish</wp:status>
    <wp:comment_status>closed</wp:comment_status>
    <wp:post_name>cart</wp:post_name>
    <wp:postmeta>
      <wp:meta_key>_wp_page_template</wp:meta_key>
      <wp:meta_value><![CDATA[woocommerce/cart.php]]></wp:meta_value>
    </wp:postmeta>
  </item>
  <item>
    <title>Checkout</title>
    <dc:creator><![CDATA[admin]]></dc:creator>
    <content:encoded><![CDATA[<!-- wp:paragraph --><p>Place your order.</p><!-- /wp:paragraph -->]]></content:encoded>
    <wp:post_id>41</wp:post_id>
    <wp:post_date>${now}</wp:post_date>
    <wp:post_type>page</wp:post_type>
    <wp:status>publish</wp:status>
    <wp:comment_status>closed</wp:comment_status>
    <wp:post_name>checkout</wp:post_name>
    <wp:postmeta>
      <wp:meta_key>_wp_page_template</wp:meta_key>
      <wp:meta_value><![CDATA[woocommerce/checkout.php]]></wp:meta_value>
    </wp:postmeta>
  </item>
  <item>
    <title>My Account</title>
    <dc:creator><![CDATA[admin]]></dc:creator>
    <content:encoded><![CDATA[<!-- wp:paragraph --><p>Manage your account.</p><!-- /wp:paragraph -->]]></content:encoded>
    <wp:post_id>42</wp:post_id>
    <wp:post_date>${now}</wp:post_date>
    <wp:post_type>page</wp:post_type>
    <wp:status>publish</wp:status>
    <wp:comment_status>closed</wp:comment_status>
    <wp:post_name>my-account</wp:post_name>
    <wp:postmeta>
      <wp:meta_key>_wp_page_template</wp:meta_key>
      <wp:meta_value><![CDATA[woocommerce/myaccount.php]]></wp:meta_value>
    </wp:postmeta>
  </item>
  ` : ''}
</channel>
</rss>`;
  }

  private xmlEsc(s: string): string {
    return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
  }

  private getConstant(suffix: string): string {
    return WordPressFileBuilder.strtoupper(this.options.themeSlug) + '_' + suffix;
  }

  private static strtoupper(s: string): string {
    return s.replace(/-/g, '_').toUpperCase();
  }
}
