import type { SectionTemplate } from '../types.js';

export const ABOUT_TEMPLATE: SectionTemplate = {
  key: 'about',
  label: 'About Section',
  description: 'About us with text, image, and stats',
  templateType: 'section',
  category: 'basic',
  relevantFor: ['ecommerce', 'blog', 'business', 'portfolio', 'landing'],
  icon: 'file-text',
  enabled: true,
  containerSettings: {
    content_width: { size: 1140, unit: 'px' },
    gap: 'no',
    padding: { top: 80, right: 20, bottom: 80, left: 20, unit: 'px' },
    columns: 2,
    column_position: 'stretch',
  },
  widgetGroups: [
    {
      key: 'left-column',
      label: 'Left Column',
      description: 'Text content for about section',
      min: 1,
      widgets: [
        {
          widgetType: 'heading',
          label: 'Section Title',
          description: 'About section heading',
          icon: 'type',
          required: true,
          defaultSettings: {
            title: 'About Us',
            html_tag: 'h2',
            size: { size: 36, unit: 'px' },
            align: 'left',
            color: '#1a1a2e',
            weight: '700',
          },
        },
        {
          widgetType: 'text-editor',
          label: 'Description',
          description: 'About text content',
          icon: 'align-left',
          required: true,
          defaultSettings: {
            editor: '<p>We are a passionate team dedicated to delivering exceptional solutions. With years of experience, we bring your ideas to life.</p><p>Our mission is to empower businesses with cutting-edge technology and creative design.</p>',
            align: 'left',
            color: '#666666',
            size: { size: 16, unit: 'px' },
            drop_cap: 'no',
          },
        },
        {
          widgetType: 'button',
          label: 'Learn More Button',
          description: 'Link to about page',
          icon: 'square-mouse-pointer',
          required: false,
          defaultSettings: {
            text: 'Learn More →',
            link: { url: '/about/', is_external: 'no', nofollow: 'no' },
            button_size: 'md',
            button_type: 'default',
            icon: '',
            icon_align: 'right',
            hover_animation: 'grow',
          },
        },
        {
          widgetType: 'progress',
          label: 'Skills Bars',
          description: 'Progress bars showing skills',
          icon: 'bar-chart-3',
          required: false,
          multi: true,
          defaultSettings: {
            title: 'Web Design',
            percent: 90,
            display_percentage: 'yes',
            inner_text: 'Web Design',
            progress_type: 'custom',
            progress_background_color: '#4A90D9',
            title_color: '#333333',
          },
        },
      ],
    },
    {
      key: 'right-column',
      label: 'Right Column',
      description: 'Image and stats',
      max: 2,
      widgets: [
        {
          widgetType: 'image',
          label: 'Featured Image',
          description: 'About section image',
          icon: 'image',
          required: true,
          defaultSettings: {
            image: { url: '', id: '', size: 'large', source: 'library' },
            image_size: 'large',
            align: 'center',
            width: { size: 100, unit: '%' },
            caption_source: 'none',
            link_to: 'none',
            hover_animation: 'zoom-in',
            border_radius: { size: 8, unit: 'px', top: 8, right: 8, bottom: 8, left: 8 },
          },
        },
        {
          widgetType: 'counter',
          label: 'Stats Counter',
          description: 'Animated number counter',
          icon: 'plus-circle',
          required: false,
          multi: true,
          defaultSettings: {
            starting_number: 0,
            ending_number: 100,
            prefix: '',
            suffix: '+',
            title: 'Projects',
            icon: '',
            icon_size: { size: 40, unit: 'px' },
            number_size: { size: 48, unit: 'px' },
            title_size: { size: 18, unit: 'px' },
            align: 'center',
          },
        },
      ],
    },
  ],
};

export const SERVICES_TEMPLATE: SectionTemplate = {
  key: 'services',
  label: 'Services Section',
  description: 'Services or features grid with icons',
  templateType: 'section',
  category: 'basic',
  relevantFor: ['ecommerce', 'business', 'portfolio', 'landing'],
  icon: 'grid-3x3',
  enabled: true,
  containerSettings: {
    content_width: { size: 1140, unit: 'px' },
    gap: 'yes',
    gap_size: { size: 30, unit: 'px' },
    padding: { top: 80, right: 20, bottom: 80, left: 20, unit: 'px' },
    columns: 3,
    background_color: '#F8F9FA',
  },
  widgetGroups: [
    {
      key: 'section-header',
      label: 'Section Header',
      description: 'Title and subtitle',
      min: 1,
      max: 2,
      widgets: [
        {
          widgetType: 'heading',
          label: 'Section Title',
          description: 'Services section heading',
          icon: 'type',
          required: true,
          defaultSettings: {
            title: 'Our Services',
            html_tag: 'h2',
            size: { size: 36, unit: 'px' },
            align: 'center',
            color: '#1a1a2e',
            weight: '700',
          },
        },
        {
          widgetType: 'text-editor',
          label: 'Section Subtitle',
          description: 'Subtitle below heading',
          icon: 'align-left',
          required: false,
          defaultSettings: {
            editor: '<p>Everything you need to grow your business</p>',
            align: 'center',
            color: '#666666',
            size: { size: 18, unit: 'px' },
          },
        },
      ],
    },
    {
      key: 'service-cards',
      label: 'Service Cards',
      description: 'Individual service cards in grid',
      min: 3,
      multi: true,
      widgets: [
        {
          widgetType: 'icon-box',
          label: 'Service Card',
          description: 'Icon with title and description',
          icon: 'box',
          required: true,
          defaultSettings: {
            icon: 'laptop',
            title_text: 'Web Development',
            description_text: 'Custom websites built with modern technologies and best practices.',
            icon_size: { size: 50, unit: 'px' },
            icon_color: '#4A90D9',
            title_size: { size: 22, unit: 'px' },
            description_size: { size: 15, unit: 'px' },
            position: 'top',
            align: 'center',
            title_html_tag: 'h3',
            hover_animation: 'float',
            background_color: '#FFFFFF',
            padding: { top: 30, right: 20, bottom: 30, left: 20, unit: 'px' },
            border_radius: { size: 8, unit: 'px' },
            box_shadow: '0px 4px 12px 0px rgba(0,0,0,0.08)',
          },
        },
        {
          widgetType: 'flip-box',
          label: 'Flip Box Card',
          description: 'Card that flips on hover',
          icon: 'rotate-3d',
          required: false,
          defaultSettings: {
            title_front: 'Web Development',
            title_back: 'Learn More',
            description_front: 'Modern websites built to scale.',
            description_back: 'We use React, Node.js, and WordPress.',
            button_text: 'Get Started',
            button_link: { url: '#', is_external: 'no', nofollow: 'no' },
            background_image_front: { url: '', id: '', size: 'full', source: 'library' },
            background_image_back: { url: '', id: '', size: 'full', source: 'library' },
          },
        },
        {
          widgetType: 'call-to-action',
          label: 'CTA Card',
          description: 'Call-to-action card with button',
          icon: 'megaphone',
          required: false,
          defaultSettings: {
            title: 'Need a Custom Solution?',
            description: 'We build tailored solutions for your unique needs.',
            button_text: 'Contact Us',
            button_link: { url: '/contact/', is_external: 'no', nofollow: 'no' },
            graphic_element: 'icon',
            icon: 'star',
            ribbon_title: 'Popular',
            cta_layout: 'standard',
          },
        },
      ],
    },
  ],
};

export const PORTFOLIO_TEMPLATE: SectionTemplate = {
  key: 'portfolio',
  label: 'Portfolio Section',
  description: 'Image gallery with filterable portfolio',
  templateType: 'section',
  category: 'media',
  relevantFor: ['business', 'portfolio', 'landing'],
  icon: 'images',
  enabled: true,
  containerSettings: {
    content_width: { size: 1140, unit: 'px' },
    gap: 'yes',
    gap_size: { size: 20, unit: 'px' },
    padding: { top: 80, right: 20, bottom: 80, left: 20, unit: 'px' },
  },
  widgetGroups: [
    {
      key: 'section-header',
      label: 'Section Header',
      description: 'Title and subtitle',
      min: 1,
      max: 2,
      widgets: [
        {
          widgetType: 'heading',
          label: 'Section Title',
          description: 'Portfolio heading',
          icon: 'type',
          required: true,
          defaultSettings: {
            title: 'Our Work',
            html_tag: 'h2',
            size: { size: 36, unit: 'px' },
            align: 'center',
            color: '#1a1a2e',
            weight: '700',
          },
        },
        {
          widgetType: 'text-editor',
          label: 'Section Subtitle',
          icon: 'align-left',
          required: false,
          defaultSettings: {
            editor: '<p>Browse our latest projects</p>',
            align: 'center',
            color: '#666666',
            size: { size: 18, unit: 'px' },
          },
        },
      ],
    },
    {
      key: 'filter-bar',
      label: 'Filter Bar',
      description: 'Taxonomy filter for portfolio',
      max: 1,
      widgets: [
        {
          widgetType: 'taxonomy-filter',
          label: 'Portfolio Filter',
          description: 'Filterable category tabs',
          icon: 'filter',
          required: false,
          defaultSettings: {
            taxonomy: 'category',
            show_counts: 'no',
            filter_type: 'dropdown',
            multiple_selection: 'no',
            filter_layout: 'horizontal',
          },
        },
      ],
    },
    {
      key: 'portfolio-grid',
      label: 'Portfolio Grid',
      description: 'The portfolio items grid',
      min: 1,
      max: 1,
      widgets: [
        {
          widgetType: 'portfolio',
          label: 'Portfolio Grid',
          description: 'Filterable image grid',
          icon: 'grid',
          required: true,
          defaultSettings: {
            columns: 3,
            posts_per_page: 9,
            item_ratio: '0.66',
            title_html_tag: 'h3',
            show_title: 'yes',
            show_filter_bar: 'yes',
            filter_by: 'category',
            image_size: 'large',
            link_to: 'custom_url',
            overlay_icon: 'plus',
            hover_animation: 'zoom-in',
          },
        },
        {
          widgetType: 'gallery',
          label: 'Image Gallery',
          description: 'Simple image gallery',
          icon: 'images',
          required: false,
          defaultSettings: {
            gallery: [],
            columns: 3,
            gallery_type: 'grid',
            link_to: 'media_file',
            open_lightbox: 'yes',
            image_size: 'large',
            hover_animation: 'zoom-in',
            aspect_ratio: '3:2',
            masonry: 'yes',
            gap: { size: 15, unit: 'px' },
          },
        },
      ],
    },
    {
      key: 'pagination',
      label: 'Pagination',
      description: 'Page navigation for portfolio',
      max: 1,
      widgets: [
        {
          widgetType: 'post-navigation',
          label: 'Pagination',
          description: 'Page navigation links',
          icon: 'chevrons-left-right',
          required: false,
          defaultSettings: {
            show_title: 'yes',
            show_arrows: 'yes',
            arrow_left: '←',
            arrow_right: '→',
            in_same_term: 'no',
            taxonomy: 'category',
          },
        },
      ],
    },
  ],
};

export const TESTIMONIALS_TEMPLATE: SectionTemplate = {
  key: 'testimonials',
  label: 'Testimonials',
  description: 'Customer reviews and testimonials carousel',
  templateType: 'section',
  category: 'basic',
  relevantFor: ['ecommerce', 'business', 'portfolio', 'landing'],
  icon: 'message-square',
  enabled: true,
  containerSettings: {
    content_width: { size: 900, unit: 'px' },
    gap: 'no',
    padding: { top: 80, right: 20, bottom: 80, left: 20, unit: 'px' },
    background_color: '#1a1a2e',
  },
  widgetGroups: [
    {
      key: 'section-header',
      label: 'Section Header',
      description: 'Title and subtitle',
      min: 1,
      max: 2,
      widgets: [
        {
          widgetType: 'heading',
          label: 'Section Title',
          description: 'Testimonials heading',
          icon: 'type',
          required: true,
          defaultSettings: {
            title: 'What Our Clients Say',
            html_tag: 'h2',
            size: { size: 36, unit: 'px' },
            align: 'center',
            color: '#FFFFFF',
            weight: '700',
          },
        },
        {
          widgetType: 'text-editor',
          label: 'Section Subtitle',
          icon: 'align-left',
          required: false,
          defaultSettings: {
            editor: '<p>Trusted by hundreds of businesses worldwide</p>',
            align: 'center',
            color: '#CCCCCC',
            size: { size: 18, unit: 'px' },
          },
        },
      ],
    },
    {
      key: 'testimonial-carousel',
      label: 'Testimonial Carousel',
      description: 'Customer review cards in carousel',
      min: 1,
      max: 2,
      widgets: [
        {
          widgetType: 'testimonial-carousel',
          label: 'Testimonial Carousel',
          description: 'Auto-playing testimonial slider',
          icon: 'chevron-right-square',
          required: true,
          defaultSettings: {
            testimonials: [
              { _id: 'rev1', name: 'John Doe', title: 'CEO, Tech Corp', rating: 5, image: { url: '', id: '', size: 'thumbnail', source: 'library' }, review: 'Excellent service! Highly recommended.', stars: 5 },
              { _id: 'rev2', name: 'Jane Smith', title: 'Founder, Design Co', rating: 5, image: { url: '', id: '', size: 'thumbnail', source: 'library' }, review: 'Transformed our online presence.', stars: 5 },
              { _id: 'rev3', name: 'Mike Johnson', title: 'Director, Startup Inc', rating: 5, image: { url: '', id: '', size: 'thumbnail', source: 'library' }, review: 'Professional team, amazing results.', stars: 4 },
            ],
            navigation: 'arrows',
            slide_animation: 'slide',
            animation_speed: 500,
            slides_to_show: 2,
            slides_to_scroll: 1,
            autoplay: 'yes',
            autoplay_speed: 4000,
            pause_on_hover: 'yes',
            infinite: 'yes',
            skin: 'skin1',
          },
        },
        {
          widgetType: 'testimonial',
          label: 'Single Testimonial',
          description: 'Static testimonial widget',
          icon: 'message-circle',
          required: false,
          defaultSettings: {
            testimonial_content: '<p>Amazing work! Would recommend to everyone.</p>',
            name: 'Sarah Williams',
            title: 'Marketing Manager',
            image: { url: '', id: '', size: 'thumbnail', source: 'library' },
            link: { url: '', is_external: 'no', nofollow: 'no' },
            testimonial_alignment: 'center',
            testimonial_layout: 'default',
          },
        },
        {
          widgetType: 'reviews',
          label: 'Reviews Widget',
          description: 'Review cards with star ratings',
          icon: 'star',
          required: false,
          defaultSettings: {
            reviews: [
              { _id: 'r1', name: 'Alice W.', title: 'Verified Buyer', rating: 5, image: { url: '', id: '', size: 'thumbnail', source: 'library' }, review: 'Great product!', stars: 5 },
              { _id: 'r2', name: 'Bob K.', title: 'Verified Buyer', rating: 4, image: { url: '', id: '', size: 'thumbnail', source: 'library' }, review: 'Very satisfied with the quality.', stars: 4 },
            ],
          },
        },
      ],
    },
  ],
};

export const PRICING_TEMPLATE: SectionTemplate = {
  key: 'pricing',
  label: 'Pricing Section',
  description: 'Pricing tables with feature comparison',
  templateType: 'section',
  category: 'basic',
  relevantFor: ['business', 'landing', 'ecommerce'],
  icon: 'credit-card',
  enabled: true,
  containerSettings: {
    content_width: { size: 1140, unit: 'px' },
    gap: 'yes',
    gap_size: { size: 30, unit: 'px' },
    padding: { top: 80, right: 20, bottom: 80, left: 20, unit: 'px' },
    columns: 3,
    background_color: '#F8F9FA',
  },
  widgetGroups: [
    {
      key: 'section-header',
      label: 'Section Header',
      description: 'Title and subtitle',
      min: 1,
      max: 2,
      widgets: [
        {
          widgetType: 'heading',
          label: 'Section Title',
          icon: 'type',
          required: true,
          defaultSettings: {
            title: 'Pricing Plans',
            html_tag: 'h2',
            size: { size: 36, unit: 'px' },
            align: 'center',
            color: '#1a1a2e',
            weight: '700',
          },
        },
        {
          widgetType: 'text-editor',
          label: 'Section Subtitle',
          icon: 'align-left',
          required: false,
          defaultSettings: {
            editor: '<p>Choose the plan that fits your needs</p>',
            align: 'center',
            color: '#666666',
            size: { size: 18, unit: 'px' },
          },
        },
      ],
    },
    {
      key: 'pricing-cards',
      label: 'Pricing Cards',
      description: 'Pricing table columns',
      min: 2,
      multi: true,
      widgets: [
        {
          widgetType: 'price-table',
          label: 'Pricing Table',
          description: 'Feature list with price',
          icon: 'dollar-sign',
          required: true,
          defaultSettings: {
            title: 'Basic',
            price: '$19',
            period: '/month',
            original_price: '$29',
            currency_symbol: '$',
            currency_position: 'before',
            period_position: 'after',
            features_list: [
              { _id: 'f1', text: '1 Website', item_description: '' },
              { _id: 'f2', text: '10 GB Storage', item_description: '' },
              { _id: 'f3', text: 'Basic Support', item_description: '' },
              { _id: 'f4', text: 'Free SSL', item_description: '' },
            ],
            button_text: 'Get Started',
            button_link: { url: '#', is_external: 'no', nofollow: 'no' },
            featured: 'no',
            featured_text: '',
            button_type: 'default',
          },
        },
        {
          widgetType: 'price-list',
          label: 'Price List',
          description: 'Menu-style itemized prices',
          icon: 'list',
          required: false,
          defaultSettings: {
            price_list: [
              { _id: 'pl1', title: 'Basic Package', price: '$19', description: 'Essential features', image: { url: '', id: '', size: 'thumbnail', source: 'library' }, link: { url: '', is_external: 'no', nofollow: 'no' } },
              { _id: 'pl2', title: 'Pro Package', price: '$49', description: 'Advanced features', image: { url: '', id: '', size: 'thumbnail', source: 'library' }, link: { url: '', is_external: 'no', nofollow: 'no' } },
              { _id: 'pl3', title: 'Enterprise', price: '$99', description: 'Full suite', image: { url: '', id: '', size: 'thumbnail', source: 'library' }, link: { url: '', is_external: 'no', nofollow: 'no' } },
            ],
          },
        },
      ],
    },
  ],
};

export const TEAM_TEMPLATE: SectionTemplate = {
  key: 'team',
  label: 'Team Section',
  description: 'Team member cards with photos and bios',
  templateType: 'section',
  category: 'basic',
  relevantFor: ['business', 'portfolio', 'landing'],
  icon: 'users',
  enabled: true,
  containerSettings: {
    content_width: { size: 1140, unit: 'px' },
    gap: 'yes',
    gap_size: { size: 30, unit: 'px' },
    padding: { top: 80, right: 20, bottom: 80, left: 20, unit: 'px' },
    columns: 4,
  },
  widgetGroups: [
    {
      key: 'section-header',
      label: 'Section Header',
      description: 'Title and subtitle',
      min: 1,
      max: 2,
      widgets: [
        {
          widgetType: 'heading',
          label: 'Section Title',
          icon: 'type',
          required: true,
          defaultSettings: {
            title: 'Meet Our Team',
            html_tag: 'h2',
            size: { size: 36, unit: 'px' },
            align: 'center',
            color: '#1a1a2e',
            weight: '700',
          },
        },
        {
          widgetType: 'text-editor',
          label: 'Section Subtitle',
          icon: 'align-left',
          required: false,
          defaultSettings: {
            editor: '<p>Talented professionals dedicated to your success</p>',
            align: 'center',
            color: '#666666',
            size: { size: 18, unit: 'px' },
          },
        },
      ],
    },
    {
      key: 'member-cards',
      label: 'Member Cards',
      description: 'Individual team member profiles',
      min: 1,
      multi: true,
      widgets: [
        {
          widgetType: 'image-box',
          label: 'Team Member',
          description: 'Photo, name, title, social links',
          icon: 'user',
          required: true,
          defaultSettings: {
            image: { url: '', id: '', size: 'medium', source: 'library' },
            title_text: 'John Doe',
            description_text: 'CEO & Founder',
            title_size: { size: 20, unit: 'px' },
            description_size: { size: 14, unit: 'px' },
            title_color: '#1a1a2e',
            description_color: '#666666',
            position: 'top',
            align: 'center',
            image_size: 'medium',
            hover_animation: 'zoom-in',
            image_shape: 'circle',
            image_width: { size: 150, unit: 'px' },
            link: { url: '', is_external: 'no', nofollow: 'no' },
          },
        },
        {
          widgetType: 'share-buttons',
          label: 'Social Links',
          description: 'Social media share buttons',
          icon: 'share-2',
          required: false,
          defaultSettings: {
            share_buttons: [
              { _id: 'sb1', button: 'facebook', text: 'Facebook', icon: { value: 'fab fa-facebook-f', library: 'fa-brands' } },
              { _id: 'sb2', button: 'twitter', text: 'Twitter', icon: { value: 'fab fa-twitter', library: 'fa-brands' } },
              { _id: 'sb3', button: 'linkedin', text: 'LinkedIn', icon: { value: 'fab fa-linkedin-in', library: 'fa-brands' } },
            ],
            skin: 'gradient',
            icons_position: 'before_text',
            alignment: 'center',
            share_url_type: 'custom',
            share_url: '',
            share_title: '',
            share_description: '',
          },
        },
      ],
    },
  ],
};

export const FAQ_TEMPLATE: SectionTemplate = {
  key: 'faq',
  label: 'FAQ Section',
  description: 'Frequently asked questions accordion',
  templateType: 'section',
  category: 'basic',
  relevantFor: ['ecommerce', 'business', 'portfolio', 'landing'],
  icon: 'help-circle',
  enabled: true,
  containerSettings: {
    content_width: { size: 800, unit: 'px' },
    gap: 'no',
    padding: { top: 80, right: 20, bottom: 80, left: 20, unit: 'px' },
  },
  widgetGroups: [
    {
      key: 'section-header',
      label: 'Section Header',
      description: 'Title and subtitle',
      min: 1,
      max: 2,
      widgets: [
        {
          widgetType: 'heading',
          label: 'Section Title',
          icon: 'type',
          required: true,
          defaultSettings: {
            title: 'Frequently Asked Questions',
            html_tag: 'h2',
            size: { size: 36, unit: 'px' },
            align: 'center',
            color: '#1a1a2e',
            weight: '700',
          },
        },
      ],
    },
    {
      key: 'faq-items',
      label: 'FAQ Items',
      description: 'The accordion FAQ items',
      min: 3,
      widgets: [
        {
          widgetType: 'accordion',
          label: 'FAQ Accordion',
          description: 'Expandable Q&A items',
          icon: 'chevrons-down-up',
          required: true,
          defaultSettings: {
            tabs: [
              { _id: 'faq1', tab_title: 'What services do you offer?', tab_content: '<p>We offer a comprehensive range of services including web development, mobile apps, UI/UX design, and digital marketing.</p>' },
              { _id: 'faq2', tab_title: 'How much does it cost?', tab_content: '<p>Our pricing varies based on project scope. Contact us for a customized quote.</p>' },
              { _id: 'faq3', tab_title: 'What is the typical timeline?', tab_content: '<p>Projects typically take 4-8 weeks depending on complexity and requirements.</p>' },
              { _id: 'faq4', tab_title: 'Do you offer support after launch?', tab_content: '<p>Yes, we provide ongoing maintenance and support packages to keep your site running smoothly.</p>' },
            ],
            title_html_tag: 'div',
            icon: 'plus',
            icon_active: 'minus',
            icon_position: 'left',
            toggle_speed: 300,
            accordion_type: 'accordion',
          },
        },
        {
          widgetType: 'toggle',
          label: 'FAQ Toggle',
          description: 'Independent toggle items',
          icon: 'plus-minus',
          required: false,
          defaultSettings: {
            tabs: [
              { _id: 'tg1', tab_title: 'Question 1', tab_content: '<p>Answer to question 1.</p>' },
              { _id: 'tg2', tab_title: 'Question 2', tab_content: '<p>Answer to question 2.</p>' },
            ],
            title_html_tag: 'div',
            icon: 'plus',
            icon_active: 'minus',
            icon_position: 'left',
            toggle_speed: 300,
          },
        },
      ],
    },
  ],
};

export const CONTACT_TEMPLATE: SectionTemplate = {
  key: 'contact',
  label: 'Contact Section',
  description: 'Contact form with info sidebar',
  templateType: 'section',
  category: 'form',
  relevantFor: ['ecommerce', 'blog', 'business', 'portfolio', 'landing'],
  icon: 'mail',
  enabled: true,
  containerSettings: {
    content_width: { size: 1140, unit: 'px' },
    gap: 'no',
    padding: { top: 80, right: 20, bottom: 80, left: 20, unit: 'px' },
    columns: 2,
    background_color: '#F8F9FA',
  },
  widgetGroups: [
    {
      key: 'contact-info',
      label: 'Contact Info',
      description: 'Address, phone, email, social links',
      min: 1,
      widgets: [
        {
          widgetType: 'heading',
          label: 'Contact Heading',
          icon: 'type',
          required: true,
          defaultSettings: {
            title: 'Get In Touch',
            html_tag: 'h3',
            size: { size: 28, unit: 'px' },
            align: 'left',
            color: '#1a1a2e',
            weight: '700',
          },
        },
        {
          widgetType: 'icon-list',
          label: 'Contact Details',
          description: 'List of contact info with icons',
          icon: 'list',
          required: true,
          defaultSettings: {
            icon_list: [
              { _id: 'cl1', text: '123 Business Ave, Suite 100', icon: 'map-pin', link: { url: '', is_external: 'yes', nofollow: 'no' } },
              { _id: 'cl2', text: 'info@example.com', icon: 'envelope', link: { url: 'mailto:info@example.com', is_external: 'no', nofollow: 'no' } },
              { _id: 'cl3', text: '+1 (555) 123-4567', icon: 'phone', link: { url: 'tel:+15551234567', is_external: 'no', nofollow: 'no' } },
            ],
            icon_size: { size: 16, unit: 'px' },
            icon_color: '#4A90D9',
            text_color: '#333333',
            text_size: { size: 16, unit: 'px' },
            space_between: { size: 15, unit: 'px' },
            icon_align: 'left',
            view: 'traditional',
          },
        },
        {
          widgetType: 'share-buttons',
          label: 'Social Links',
          icon: 'share-2',
          required: false,
          defaultSettings: {
            share_buttons: [
              { _id: 'sb1', button: 'facebook', text: '', icon: { value: 'fab fa-facebook-f', library: 'fa-brands' } },
              { _id: 'sb2', button: 'twitter', text: '', icon: { value: 'fab fa-twitter', library: 'fa-brands' } },
              { _id: 'sb3', button: 'instagram', text: '', icon: { value: 'fab fa-instagram', library: 'fa-brands' } },
            ],
            skin: 'flat',
            icons_position: 'before_text',
            alignment: 'left',
          },
        },
      ],
    },
    {
      key: 'contact-form',
      label: 'Contact Form',
      description: 'Contact form with fields',
      min: 1,
      max: 1,
      widgets: [
        {
          widgetType: 'form',
          label: 'Contact Form Widget',
          description: 'Elementor Pro form with fields',
          icon: 'input',
          required: true,
          defaultSettings: {
            form_name: 'Contact Form',
            form_fields: [
              { _id: 'cf1', field_type: 'text', field_label: 'Name', placeholder: 'Your Name', required: 'yes', field_size: 'sm', width: '100', allow_multiple: '', file_sizes: '', file_types: '' },
              { _id: 'cf2', field_type: 'email', field_label: 'Email', placeholder: 'your@email.com', required: 'yes', field_size: 'sm', width: '100', allow_multiple: '', file_sizes: '', file_types: '' },
              { _id: 'cf3', field_type: 'text', field_label: 'Subject', placeholder: 'How can we help?', required: 'no', field_size: 'sm', width: '100', allow_multiple: '', file_sizes: '', file_types: '' },
              { _id: 'cf4', field_type: 'textarea', field_label: 'Message', placeholder: 'Your message...', required: 'yes', field_size: 'sm', width: '100', allow_multiple: '', file_sizes: '', file_types: '' },
            ],
            submit_actions: ['email', 'webhook'],
            email_to: '{admin_email}',
            email_subject: 'New Contact Form Submission',
            email_content: 'Name: {field_id="cf1"}\nEmail: {field_id="cf2"}\nMessage: {field_id="cf4"}',
            email_from: '{field_id="cf2"}',
            email_from_name: '{field_id="cf1"}',
            submit_button_text: 'Send Message',
            button_size: 'md',
            button_type: 'default',
            hover_animation: 'grow',
            custom_messages: { success: 'Your message has been sent!', error: 'An error occurred.', required_field: 'This field is required.', invalid_email: 'Invalid email address.', invalid_message: 'Invalid message.' },
          },
        },
        {
          widgetType: 'newsletter-form',
          label: 'Newsletter Form',
          description: 'Email subscription form',
          icon: 'mail-plus',
          required: false,
          defaultSettings: {
            form_name: 'Newsletter',
            form_fields: [
              { _id: 'nf1', field_type: 'email', field_label: 'Email', placeholder: 'your@email.com', required: 'yes', field_size: 'sm', width: '100' },
            ],
            submit_actions: ['email'],
            email_to: '{admin_email}',
            email_subject: 'New Newsletter Subscriber',
            email_content: 'Email: {field_id="nf1"}',
            submit_button_text: 'Subscribe',
            button_size: 'md',
            button_type: 'default',
          },
        },
      ],
    },
  ],
};
