import type { SectionTemplate } from '../types.js';

export const PRODUCT_SINGLE_TEMPLATE: SectionTemplate = {
  key: 'product-single',
  label: 'Single Product Page',
  description: 'Full WooCommerce product page layout',
  templateType: 'product',
  category: 'woocommerce',
  relevantFor: ['ecommerce'],
  icon: 'package',
  enabled: true,
  containerSettings: {
    content_width: { size: 1140, unit: 'px' },
    gap: 'no',
    columns: 2,
    padding: { top: 40, right: 20, bottom: 40, left: 20, unit: 'px' },
  },
  widgetGroups: [
    {
      key: 'product-gallery',
      label: 'Product Gallery',
      description: 'Product images and thumbnails',
      min: 1,
      max: 1,
      widgets: [
        {
          widgetType: 'woocommerce-product-images',
          label: 'Product Images',
          description: 'Main image with gallery thumbnails',
          icon: 'image',
          required: true,
          defaultSettings: {
            zoom: 'yes',
            lightbox: 'yes',
            thumbnails: 'yes',
            thumbnail_position: 'bottom',
            thumbnail_size: { size: 150, unit: 'px' },
            image_size: 'large',
          },
        },
      ],
    },
    {
      key: 'product-summary',
      label: 'Product Summary',
      description: 'Title, price, rating, add to cart',
      min: 3,
      widgets: [
        {
          widgetType: 'woocommerce-breadcrumbs',
          label: 'Product Breadcrumbs',
          description: 'Breadcrumb navigation',
          icon: 'chevrons-right',
          required: false,
          defaultSettings: {
            home_text: 'Home',
            show_home: 'yes',
            home_link: 'yes',
            separator_icon: 'fas fa-chevron-right',
          },
        },
        {
          widgetType: 'woocommerce-product-title',
          label: 'Product Title',
          description: 'Dynamic product title',
          icon: 'type',
          required: true,
          defaultSettings: {
            html_tag: 'h1',
            size: { size: 28, unit: 'px' },
            color: '#1a1a2e',
            weight: '700',
          },
          dynamicTags: { title: '[elementor-tag id="" name="woocommerce-product-title" settings=""]' },
        },
        {
          widgetType: 'woocommerce-product-rating',
          label: 'Product Rating',
          description: 'Star rating and review count',
          icon: 'star',
          required: false,
          defaultSettings: {
            rating_type: 'star',
            scale: 5,
            star_style: 'star',
            show_labels: 'yes',
          },
        },
        {
          widgetType: 'woocommerce-product-price',
          label: 'Product Price',
          description: 'Dynamic product price',
          icon: 'dollar-sign',
          required: true,
          defaultSettings: {
            size: { size: 24, unit: 'px' },
            align: 'left',
            color: '#4A90D9',
            weight: '700',
            sale_color: '#e74c3c',
          },
          dynamicTags: { price: '[elementor-tag id="" name="woocommerce-product-price" settings=""]' },
        },
        {
          widgetType: 'woocommerce-product-stock',
          label: 'Product Stock',
          description: 'Stock status indicator',
          icon: 'package',
          required: false,
          defaultSettings: {
            stock_display_type: 'text',
          },
        },
        {
          widgetType: 'woocommerce-product-short-description',
          label: 'Short Description',
          description: 'Product excerpt',
          icon: 'align-left',
          required: false,
          defaultSettings: {
            size: { size: 16, unit: 'px' },
            color: '#666666',
          },
        },
        {
          widgetType: 'woocommerce-product-add-to-cart',
          label: 'Add to Cart',
          description: 'Quantity selector and add to cart button',
          icon: 'shopping-cart',
          required: true,
          defaultSettings: {
            quantity: 'yes',
            variations: 'yes',
            button_text: 'Add to Cart',
            button_size: 'md',
            ajax_add_to_cart: 'yes',
            button_background_color: '#4A90D9',
            button_text_color: '#FFFFFF',
          },
        },
        {
          widgetType: 'woocommerce-product-meta',
          label: 'Product Meta',
          description: 'SKU, categories, tags',
          icon: 'info',
          required: false,
          defaultSettings: {
            sku: 'yes',
            categories: 'yes',
            tags: 'yes',
            size: { size: 14, unit: 'px' },
            color: '#666666',
          },
        },
      ],
    },
    {
      key: 'product-tabs',
      label: 'Product Tabs',
      description: 'Description, additional info, reviews',
      max: 1,
      widgets: [
        {
          widgetType: 'woocommerce-product-data-tabs',
          label: 'Product Data Tabs',
          description: 'Tabbed product information',
          icon: 'columns',
          required: true,
          defaultSettings: {
            product_tabs: ['description', 'additional_information', 'reviews'],
            layout: 'horizontal',
            size: { size: 16, unit: 'px' },
            color: '#333333',
          },
        },
      ],
    },
    {
      key: 'product-related',
      label: 'Related Products',
      description: 'Related and upsell products',
      widgets: [
        {
          widgetType: 'woocommerce-product-related',
          label: 'Related Products',
          description: 'Related product grid',
          icon: 'grid',
          required: true,
          defaultSettings: {
            columns: 4,
            posts_per_page: 4,
            orderby: 'rand',
            order: 'desc',
          },
        },
        {
          widgetType: 'woocommerce-upsells',
          label: 'Upsells',
          description: 'Up-sell product suggestions',
          icon: 'arrow-up',
          required: false,
          defaultSettings: {
            columns: 4,
            posts_per_page: 4,
            orderby: 'rand',
            order: 'desc',
          },
        },
      ],
    },
  ],
};

export const PRODUCT_GRID_TEMPLATE: SectionTemplate = {
  key: 'product-grid',
  label: 'Product Grid / Shop',
  description: 'Product catalog with grid, filter, pagination',
  templateType: 'product-archive',
  category: 'woocommerce',
  relevantFor: ['ecommerce'],
  icon: 'shopping-bag',
  enabled: true,
  containerSettings: {
    content_width: { size: 1140, unit: 'px' },
    gap: 'yes',
    gap_size: { size: 30, unit: 'px' },
    padding: { top: 60, right: 20, bottom: 60, left: 20, unit: 'px' },
  },
  widgetGroups: [
    {
      key: 'archive-header',
      label: 'Archive Header',
      description: 'Page title, breadcrumbs, result count',
      max: 3,
      widgets: [
        {
          widgetType: 'woocommerce-breadcrumbs',
          label: 'Shop Breadcrumbs',
          icon: 'chevrons-right',
          required: false,
          defaultSettings: {
            home_text: 'Home',
            show_home: 'yes',
            home_link: 'yes',
            separator_icon: 'fas fa-chevron-right',
          },
        },
        {
          widgetType: 'woocommerce-archive-title',
          label: 'Archive Title',
          description: 'Shop page title',
          icon: 'type',
          required: true,
          defaultSettings: {
            html_tag: 'h1',
            size: { size: 32, unit: 'px' },
            color: '#1a1a2e',
            weight: '700',
          },
        },
        {
          widgetType: 'woocommerce-archive-description',
          label: 'Archive Description',
          icon: 'align-left',
          required: false,
          defaultSettings: {
            size: { size: 16, unit: 'px' },
            color: '#666666',
          },
        },
        {
          widgetType: 'woocommerce-notices',
          label: 'WooCommerce Notices',
          description: 'Success/error messages',
          icon: 'bell',
          required: true,
          defaultSettings: {},
        },
      ],
    },
    {
      key: 'shop-controls',
      label: 'Shop Controls',
      description: 'Catalog ordering, result count, filters',
      max: 2,
      widgets: [
        {
          widgetType: 'woocommerce-products',
          label: 'Products Grid',
          description: 'Full product grid with catalog controls',
          icon: 'grid',
          required: true,
          defaultSettings: {
            columns: 4,
            columns_tablet: 3,
            columns_mobile: 2,
            posts_per_page: 12,
            orderby: 'menu_order',
            order: 'asc',
            source: 'current_query',
            paginate: 'yes',
            allow_order: 'yes',
            show_result_count: 'yes',
            show_catalog_ordering: 'yes',
            show_cross_sells: 'no',
          },
        },
        {
          widgetType: 'taxonomy-filter',
          label: 'Product Category Filter',
          description: 'Filter by product category',
          icon: 'filter',
          required: false,
          defaultSettings: {
            taxonomy: 'product_cat',
            show_counts: 'yes',
            filter_type: 'checkbox',
            multiple_selection: 'yes',
            filter_layout: 'vertical',
          },
        },
      ],
    },
    {
      key: 'product-categories',
      label: 'Product Categories',
      description: 'Category cards grid',
      widgets: [
        {
          widgetType: 'woocommerce-categories',
          label: 'Category Cards',
          description: 'Product category grid',
          icon: 'folder',
          required: false,
          defaultSettings: {
            columns: 4,
            categories_count: 8,
            source: 'all',
            hide_empty: 'yes',
            show_title: 'yes',
            show_count: 'yes',
            show_thumbnail: 'yes',
          },
        },
      ],
    },
  ],
};

export const CART_PAGE_TEMPLATE: SectionTemplate = {
  key: 'cart-page',
  label: 'Cart Page',
  description: 'WooCommerce shopping cart layout',
  templateType: 'page',
  category: 'woocommerce',
  relevantFor: ['ecommerce'],
  icon: 'shopping-cart',
  enabled: true,
  containerSettings: {
    content_width: { size: 1140, unit: 'px' },
    gap: 'no',
    padding: { top: 60, right: 20, bottom: 60, left: 20, unit: 'px' },
  },
  widgetGroups: [
    {
      key: 'page-header',
      label: 'Page Header',
      description: 'Cart page title',
      widgets: [
        {
          widgetType: 'page-title',
          label: 'Cart Title',
          icon: 'type',
          required: true,
          defaultSettings: {
            html_tag: 'h1',
            size: { size: 32, unit: 'px' },
            color: '#1a1a2e',
            weight: '700',
          },
        },
      ],
    },
    {
      key: 'cart-content',
      label: 'Cart Content',
      description: 'Cart table and checkout',
      max: 2,
      widgets: [
        {
          widgetType: 'woocommerce-cart',
          label: 'Cart Widget',
          description: 'Full cart with table, totals, coupon',
          icon: 'table',
          required: true,
          defaultSettings: {
            cart_layout: 'two-column',
            show_cross_sells: 'yes',
            cross_sells_columns: 4,
            cross_sells_count: 4,
            show_coupon_form: 'yes',
            show_additional_info: 'yes',
            show_order_review: 'yes',
            sticky_order_review: 'no',
          },
        },
      ],
    },
  ],
};

export const CHECKOUT_PAGE_TEMPLATE: SectionTemplate = {
  key: 'checkout-page',
  label: 'Checkout Page',
  description: 'WooCommerce checkout layout',
  templateType: 'page',
  category: 'woocommerce',
  relevantFor: ['ecommerce'],
  icon: 'credit-card',
  enabled: true,
  containerSettings: {
    content_width: { size: 1140, unit: 'px' },
    gap: 'no',
    padding: { top: 60, right: 20, bottom: 60, left: 20, unit: 'px' },
  },
  widgetGroups: [
    {
      key: 'checkout-content',
      label: 'Checkout Content',
      description: 'Checkout form and order review',
      min: 1,
      max: 1,
      widgets: [
        {
          widgetType: 'woocommerce-checkout',
          label: 'Checkout Widget',
          description: 'Full checkout with billing, payment, review',
          icon: 'file-text',
          required: true,
          defaultSettings: {
            checkout_layout: 'two-column',
            sticky_checkout_button: 'no',
            place_order_text: 'Place Order',
            show_login_form: 'yes',
            show_coupon_form: 'yes',
            show_additional_info: 'yes',
            show_order_review: 'yes',
            sticky_order_review: 'yes',
          },
        },
      ],
    },
  ],
};

export const MY_ACCOUNT_TEMPLATE: SectionTemplate = {
  key: 'my-account',
  label: 'My Account Page',
  description: 'WooCommerce my account with dashboard, orders, downloads',
  templateType: 'page',
  category: 'woocommerce',
  relevantFor: ['ecommerce'],
  icon: 'user-circle',
  enabled: true,
  containerSettings: {
    content_width: { size: 1140, unit: 'px' },
    gap: 'no',
    padding: { top: 60, right: 20, bottom: 60, left: 20, unit: 'px' },
  },
  widgetGroups: [
    {
      key: 'account-content',
      label: 'My Account',
      description: 'Account dashboard with tabs',
      min: 1,
      max: 1,
      widgets: [
        {
          widgetType: 'woocommerce-my-account',
          label: 'My Account Widget',
          description: 'Full account management',
          icon: 'user',
          required: true,
          defaultSettings: {
            layout: 'horizontal',
            orders_limit: 10,
            show_downloads: 'yes',
            show_orders: 'yes',
            show_edit_account: 'yes',
            show_subscriptions: 'yes',
          },
        },
      ],
    },
  ],
};

export const PURCHASE_SUMMARY_TEMPLATE: SectionTemplate = {
  key: 'purchase-summary',
  label: 'Purchase Summary / Thank You',
  description: 'Order confirmation after checkout',
  templateType: 'page',
  category: 'woocommerce',
  relevantFor: ['ecommerce'],
  icon: 'check-circle',
  enabled: true,
  containerSettings: {
    content_width: { size: 800, unit: 'px' },
    gap: 'no',
    padding: { top: 60, right: 20, bottom: 60, left: 20, unit: 'px' },
    align_items: 'center',
    justify_content: 'center',
  },
  widgetGroups: [
    {
      key: 'summary-content',
      label: 'Order Summary',
      description: 'Thank you message and order details',
      widgets: [
        {
          widgetType: 'woocommerce-purchase-summary',
          label: 'Purchase Summary',
          description: 'Order confirmation with details',
          icon: 'check',
          required: true,
          defaultSettings: {
            show_order_details: 'yes',
            show_downloads: 'yes',
            show_payment_method: 'yes',
            show_shipping_address: 'yes',
            show_billing_address: 'yes',
            show_subscription_details: 'yes',
          },
        },
      ],
    },
  ],
};

export const LOGIN_PAGE_TEMPLATE: SectionTemplate = {
  key: 'login-page',
  label: 'Login / Register Page',
  description: 'Login, register, and password reset forms',
  templateType: 'page',
  category: 'form',
  relevantFor: ['ecommerce', 'blog', 'business'],
  icon: 'log-in',
  enabled: true,
  containerSettings: {
    content_width: { size: 500, unit: 'px' },
    gap: 'no',
    padding: { top: 100, right: 20, bottom: 100, left: 20, unit: 'px' },
    align_items: 'center',
    justify_content: 'center',
  },
  widgetGroups: [
    {
      key: 'login-form',
      label: 'Login Form',
      description: 'Login/register widget',
      min: 1,
      max: 2,
      widgets: [
        {
          widgetType: 'login',
          label: 'Login Form Widget',
          description: 'Login, register, lost password forms',
          icon: 'log-in',
          required: true,
          defaultSettings: {
            redirect_url: '/my-account/',
            logout_redirect: '',
            show_lost_password: 'yes',
            show_remember_me: 'yes',
            show_logged_in_message: 'yes',
            custom_labels: 'no',
            button_text: 'Log In',
            register_button_text: 'Register',
            lost_password_text: 'Lost your password?',
          },
        },
      ],
    },
  ],
};
