import type { SectionTemplate } from '../types.js';

export const FOOTER_TEMPLATE: SectionTemplate = {
  key: 'footer',
  label: 'Footer',
  description: 'Site footer with widgets and copyright',
  templateType: 'footer',
  category: 'basic',
  relevantFor: ['ecommerce', 'blog', 'business', 'portfolio', 'landing', 'news'],
  icon: 'layout-dashboard',
  enabled: true,
  containerSettings: {
    content_width: { size: 1140, unit: 'px' },
    gap: 'no',
    columns: 4,
    padding: { top: 60, right: 20, bottom: 30, left: 20, unit: 'px' },
    background_color: '#1a1a2e',
    color: '#FFFFFF',
  },
  widgetGroups: [
    {
      key: 'footer-widget-1',
      label: 'Footer Widget 1 — About',
      description: 'Logo, about text, social links',
      min: 1,
      widgets: [
        {
          widgetType: 'site-logo',
          label: 'Footer Logo',
          icon: 'image',
          required: true,
          defaultSettings: {
            image: { url: '', id: '', size: 'full', source: 'site' },
            width: { size: 150, unit: 'px' },
            align: 'left',
            link: { url: '{{home_url}}', is_external: 'no', nofollow: 'no' },
          },
          dynamicTags: { image: '[elementor-tag id="" name="site-logo" settings="%7B%22responsive%22%3A%22%22%7D"]' },
        },
        {
          widgetType: 'text-editor',
          label: 'About Text',
          description: 'Brief company description',
          icon: 'align-left',
          required: true,
          defaultSettings: {
            editor: '<p>We are dedicated to providing the best solutions for your business needs.</p>',
            align: 'left',
            color: '#CCCCCC',
            size: { size: 14, unit: 'px' },
          },
        },
        {
          widgetType: 'share-buttons',
          label: 'Social Icons',
          icon: 'share-2',
          required: false,
          defaultSettings: {
            share_buttons: [
              { _id: 'sbf1', button: 'facebook', text: '', icon: { value: 'fab fa-facebook-f', library: 'fa-brands' } },
              { _id: 'sbf2', button: 'twitter', text: '', icon: { value: 'fab fa-twitter', library: 'fa-brands' } },
              { _id: 'sbf3', button: 'linkedin', text: '', icon: { value: 'fab fa-linkedin-in', library: 'fa-brands' } },
              { _id: 'sbf4', button: 'instagram', text: '', icon: { value: 'fab fa-instagram', library: 'fa-brands' } },
            ],
            skin: 'flat',
            icons_position: 'before_text',
            alignment: 'left',
            icon_color: '#FFFFFF',
            icon_hover_color: '#4A90D9',
          },
        },
      ],
    },
    {
      key: 'footer-widget-2',
      label: 'Footer Widget 2 — Quick Links',
      description: 'Navigation links',
      widgets: [
        {
          widgetType: 'heading',
          label: 'Widget Title',
          icon: 'type',
          required: true,
          defaultSettings: {
            title: 'Quick Links',
            html_tag: 'h4',
            size: { size: 18, unit: 'px' },
            align: 'left',
            color: '#FFFFFF',
            weight: '600',
          },
        },
        {
          widgetType: 'wp-widget-pages',
          label: 'Pages List',
          description: 'WordPress pages widget',
          icon: 'file',
          required: true,
          defaultSettings: {
            wp_widget_type: 'pages',
            title: '',
            sortby: 'menu_order',
            exclude: '',
            show_home: 'no',
          },
        },
      ],
    },
    {
      key: 'footer-widget-3',
      label: 'Footer Widget 3 — Services',
      description: 'Service links',
      widgets: [
        {
          widgetType: 'heading',
          label: 'Widget Title',
          icon: 'type',
          required: true,
          defaultSettings: {
            title: 'Services',
            html_tag: 'h4',
            size: { size: 18, unit: 'px' },
            align: 'left',
            color: '#FFFFFF',
            weight: '600',
          },
        },
        {
          widgetType: 'icon-list',
          label: 'Service Links',
          description: 'List of service links',
          icon: 'list',
          required: true,
          defaultSettings: {
            icon_list: [
              { _id: 'fl1', text: 'Web Development', icon: 'chevron-right', link: { url: '/services/web-development/', is_external: 'no', nofollow: 'no' } },
              { _id: 'fl2', text: 'Mobile Apps', icon: 'chevron-right', link: { url: '/services/mobile-apps/', is_external: 'no', nofollow: 'no' } },
              { _id: 'fl3', text: 'UI/UX Design', icon: 'chevron-right', link: { url: '/services/ui-ux/', is_external: 'no', nofollow: 'no' } },
              { _id: 'fl4', text: 'Digital Marketing', icon: 'chevron-right', link: { url: '/services/marketing/', is_external: 'no', nofollow: 'no' } },
            ],
            icon_size: { size: 12, unit: 'px' },
            icon_color: '#4A90D9',
            text_color: '#CCCCCC',
            text_size: { size: 14, unit: 'px' },
            space_between: { size: 10, unit: 'px' },
            icon_align: 'left',
            view: 'traditional',
          },
        },
      ],
    },
    {
      key: 'footer-widget-4',
      label: 'Footer Widget 4 — Contact',
      description: 'Contact info and newsletter',
      widgets: [
        {
          widgetType: 'heading',
          label: 'Widget Title',
          icon: 'type',
          required: true,
          defaultSettings: {
            title: 'Contact',
            html_tag: 'h4',
            size: { size: 18, unit: 'px' },
            align: 'left',
            color: '#FFFFFF',
            weight: '600',
          },
        },
        {
          widgetType: 'icon-list',
          label: 'Contact Info',
          icon: 'list',
          required: true,
          defaultSettings: {
            icon_list: [
              { _id: 'fc1', text: 'info@example.com', icon: 'envelope', link: { url: 'mailto:info@example.com', is_external: 'no', nofollow: 'no' } },
              { _id: 'fc2', text: '+1 (555) 123-4567', icon: 'phone', link: { url: 'tel:+15551234567', is_external: 'no', nofollow: 'no' } },
            ],
            icon_size: { size: 14, unit: 'px' },
            icon_color: '#4A90D9',
            text_color: '#CCCCCC',
            text_size: { size: 14, unit: 'px' },
            icon_align: 'left',
          },
        },
        {
          widgetType: 'newsletter-form',
          label: 'Newsletter Signup',
          description: 'Minimal email signup',
          icon: 'mail-plus',
          required: false,
          defaultSettings: {
            form_name: 'Footer Newsletter',
            form_fields: [
              { _id: 'ff1', field_type: 'email', field_label: 'Email', placeholder: 'Your email', required: 'yes', field_size: 'sm', width: '100' },
            ],
            submit_button_text: 'Subscribe',
            button_size: 'sm',
            button_type: 'default',
            submit_actions: ['email'],
            email_to: '{admin_email}',
            email_subject: 'New Footer Subscriber',
          },
        },
      ],
    },
    {
      key: 'copyright-bar',
      label: 'Copyright Bar',
      description: 'Full-width copyright line below widgets',
      widgets: [
        {
          widgetType: 'text-editor',
          label: 'Copyright Text',
          description: 'Copyright notice',
          icon: 'copyright',
          required: true,
          defaultSettings: {
            editor: '<p>&copy; 2026 Your Company. All rights reserved.</p>',
            align: 'center',
            color: '#999999',
            size: { size: 13, unit: 'px' },
          },
        },
      ],
    },
  ],
};

export const BLOG_POSTS_TEMPLATE: SectionTemplate = {
  key: 'blog-posts',
  label: 'Blog Posts',
  description: 'Blog post grid with archive-style listings',
  templateType: 'archive',
  category: 'basic',
  relevantFor: ['blog', 'ecommerce', 'business', 'news'],
  icon: 'newspaper',
  enabled: true,
  containerSettings: {
    content_width: { size: 1140, unit: 'px' },
    gap: 'yes',
    gap_size: { size: 30, unit: 'px' },
    padding: { top: 80, right: 20, bottom: 80, left: 20, unit: 'px' },
    columns: 3,
  },
  widgetGroups: [
    {
      key: 'section-header',
      label: 'Section Header',
      description: 'Archive title and description',
      max: 2,
      widgets: [
        {
          widgetType: 'archive-title',
          label: 'Archive Title',
          description: 'Dynamic archive page title',
          icon: 'type',
          required: false,
          defaultSettings: {
            title: '',
            html_tag: 'h1',
            size: { size: 36, unit: 'px' },
            align: 'left',
            color: '#1a1a2e',
            weight: '700',
          },
          dynamicTags: { title: '[elementor-tag id="" name="archive-title" settings="%7B%22include_context%22%3A%22yes%22%7D"]' },
        },
        {
          widgetType: 'archive-description',
          label: 'Archive Description',
          icon: 'align-left',
          required: false,
          defaultSettings: {
            description: '',
            align: 'left',
            color: '#666666',
            size: { size: 16, unit: 'px' },
          },
          dynamicTags: { description: '[elementor-tag id="" name="archive-description" settings="%7B%22include_context%22%3A%22yes%22%7D"]' },
        },
      ],
    },
    {
      key: 'posts-grid',
      label: 'Posts Grid',
      description: 'The main posts loop',
      min: 1,
      max: 1,
      widgets: [
        {
          widgetType: 'archive-posts',
          label: 'Archive Posts Grid',
          description: 'Posts loop with pagination',
          icon: 'grid',
          required: true,
          defaultSettings: {
            skin: 'classic',
            columns: 3,
            columns_tablet: 2,
            columns_mobile: 1,
            posts_per_page: 9,
            image_position: 'top',
            masonry: '',
            image_size: 'medium_large',
            image_ratio: { size: 0.66, unit: 'px' },
            show_title: 'yes',
            title_html_tag: 'h3',
            show_excerpt: 'yes',
            excerpt_length: 25,
            meta_data: ['date', 'author', 'comments'],
            show_read_more: 'yes',
            read_more_text: 'Read More →',
            pagination_type: 'numbers',
          },
        },
        {
          widgetType: 'posts',
          label: 'Posts Widget',
          description: 'Customizable posts widget',
          icon: 'file-text',
          required: false,
          defaultSettings: {
            skin: 'classic',
            columns: 3,
            posts_per_page: 6,
            image_position: 'top',
            masonry: '',
            image_size: 'medium_large',
            show_title: 'yes',
            title_html_tag: 'h3',
            show_excerpt: 'yes',
            excerpt_length: 20,
            meta_data: ['date', 'author'],
            show_read_more: 'yes',
            read_more_text: 'Read More',
            pagination_type: 'numbers',
            query_id: '',
            orderby: 'date',
            order: 'desc',
            offset: 0,
          },
        },
        {
          widgetType: 'loop-grid',
          label: 'Loop Grid',
          description: 'Elementor Pro loop grid with template',
          icon: 'layout-grid',
          required: false,
          defaultSettings: {
            template_id: 0,
            posts_per_page: 9,
            columns: 3,
            columns_tablet: 2,
            columns_mobile: 1,
            pagination: 'numbers',
            enable_masonry: 'no',
            alternate_template: 0,
            query_id: '',
            orderby: 'date',
            order: 'desc',
          },
        },
        {
          widgetType: 'loop-carousel',
          label: 'Loop Carousel',
          description: 'Posts carousel with loop template',
          icon: 'chevrons-left-right',
          required: false,
          defaultSettings: {
            template_id: 0,
            posts_per_page: 6,
            slides_to_show: 3,
            slides_to_scroll: 1,
            autoplay: 'yes',
            autoplay_speed: 4000,
            pause_on_hover: 'yes',
            infinite: 'yes',
            navigation: 'arrows',
            image_size: 'medium',
          },
        },
      ],
    },
    {
      key: 'sidebar',
      label: 'Sidebar',
      description: 'Blog sidebar with widgets',
      widgets: [
        {
          widgetType: 'search-form',
          label: 'Search Widget',
          description: 'Blog search form',
          icon: 'search',
          required: true,
          defaultSettings: {
            skin: 'classic',
            live_search: 'no',
            placeholder: 'Search...',
            search_icon: 'yes',
            button_text: 'Search',
          },
        },
        {
          widgetType: 'wp-widget-pages',
          label: 'Recent Posts',
          description: 'Recent posts list',
          icon: 'file',
          required: false,
          defaultSettings: {
            wp_widget_type: 'recent-posts',
            title: 'Recent Posts',
            number: 5,
            show_date: 'yes',
          },
        },
        {
          widgetType: 'wp-widget-pages',
          label: 'Categories',
          description: 'Category list',
          icon: 'folder',
          required: false,
          defaultSettings: {
            wp_widget_type: 'categories',
            title: 'Categories',
            count: 'yes',
            hierarchical: 'yes',
            dropdown: 'no',
          },
        },
        {
          widgetType: 'wp-widget-pages',
          label: 'Tags',
          description: 'Tag cloud',
          icon: 'tag',
          required: false,
          defaultSettings: {
            wp_widget_type: 'tag_cloud',
            title: 'Tags',
            taxonomy: 'post_tag',
            count: 'yes',
          },
        },
        {
          widgetType: 'wp-widget-pages',
          label: 'Archives',
          description: 'Monthly archive list',
          icon: 'archive',
          required: false,
          defaultSettings: {
            wp_widget_type: 'archives',
            title: 'Archives',
            count: 'yes',
            dropdown: 'no',
          },
        },
      ],
    },
  ],
};

export const SINGLE_POST_TEMPLATE: SectionTemplate = {
  key: 'single-post',
  label: 'Single Post Template',
  description: 'Single blog post layout with full content',
  templateType: 'single-post',
  category: 'theme-builder',
  relevantFor: ['blog', 'news'],
  icon: 'file-text',
  enabled: true,
  containerSettings: {
    content_width: { size: 800, unit: 'px' },
    gap: 'no',
    padding: { top: 60, right: 20, bottom: 60, left: 20, unit: 'px' },
  },
  widgetGroups: [
    {
      key: 'post-header',
      label: 'Post Header',
      description: 'Post title, meta, featured image',
      min: 2,
      widgets: [
        {
          widgetType: 'post-title',
          label: 'Post Title',
          description: 'Dynamic post title heading',
          icon: 'type',
          required: true,
          defaultSettings: {
            html_tag: 'h1',
            size: { size: 36, unit: 'px' },
            align: 'left',
            color: '#1a1a2e',
            weight: '700',
            link: { url: '', is_external: 'no', nofollow: 'no' },
          },
          dynamicTags: { title: '[elementor-tag id="" name="post-title" settings="%7B%22responsive%22%3A%22%22%7D"]' },
        },
        {
          widgetType: 'post-info',
          label: 'Post Meta',
          description: 'Author, date, categories, tags',
          icon: 'info',
          required: true,
          defaultSettings: {
            meta_list: ['author', 'date', 'categories', 'comments'],
            separator: '|',
            show_icons: 'yes',
            show_title: 'yes',
            text_color: '#666666',
            icon_color: '#4A90D9',
            size: { size: 14, unit: 'px' },
          },
          dynamicTags: {
            author: '[elementor-tag id="" name="post-author" settings="%7B%22avatar_size%22%3A%2232%22%7D"]',
            date: '[elementor-tag id="" name="post-date" settings="%7B%22date_format%22%3A%22F+j%2C+Y%22%7D"]',
          },
        },
        {
          widgetType: 'post-featured-image',
          label: 'Featured Image',
          description: 'Post featured image',
          icon: 'image',
          required: false,
          defaultSettings: {
            image_size: 'large',
            align: 'center',
            caption_source: 'none',
            link_to: 'none',
            hover_animation: 'zoom-in',
            width: { size: 100, unit: '%' },
            border_radius: { size: 8, unit: 'px' },
          },
          dynamicTags: { image: '[elementor-tag id="" name="post-featured-image" settings="%7B%22image_size%22%3A%22large%22%7D"]' },
        },
      ],
    },
    {
      key: 'post-content-area',
      label: 'Post Content',
      description: 'Main content and author box',
      min: 1,
      widgets: [
        {
          widgetType: 'post-content',
          label: 'Post Content',
          description: 'Full dynamic post content',
          icon: 'align-left',
          required: true,
          defaultSettings: {
            editor: '',
            align: 'left',
            color: '#333333',
            size: { size: 16, unit: 'px' },
            drop_cap: 'yes',
            word_count: 0,
          },
          dynamicTags: { content: '[elementor-tag id="" name="post-content" settings="%7B%22word_count%22%3A%220%22%7D"]' },
        },
        {
          widgetType: 'post-navigation',
          label: 'Post Navigation',
          description: 'Previous/next post links',
          icon: 'chevrons-left-right',
          required: true,
          defaultSettings: {
            show_title: 'yes',
            show_arrows: 'yes',
            arrow_left: '← Previous',
            arrow_right: 'Next →',
            in_same_term: 'no',
            taxonomy: 'category',
            html_tag: 'div',
          },
        },
        {
          widgetType: 'author-box',
          label: 'Author Box',
          description: 'Post author biography',
          icon: 'user',
          required: true,
          defaultSettings: {
            author_name: '{{post_author}}',
            avatar_size: 100,
            show_biography: 'yes',
            show_icons: 'yes',
            link: { url: '{{author_archive}}', is_external: 'no', nofollow: 'no' },
            text_color: '#333333',
            name_color: '#1a1a2e',
            name_size: { size: 18, unit: 'px' },
            bio_size: { size: 14, unit: 'px' },
          },
          dynamicTags: { author_name: '[elementor-tag id="" name="post-author" settings="%7B%22avatar_size%22%3A%22100%22%7D"]' },
        },
        {
          widgetType: 'post-comments',
          label: 'Post Comments',
          description: 'WordPress comments section',
          icon: 'message-circle',
          required: false,
          defaultSettings: {
            _skin: '',
            skin: 'skin1',
          },
        },
      ],
    },
  ],
};

export const SINGLE_PAGE_TEMPLATE: SectionTemplate = {
  key: 'single-page',
  label: 'Single Page Template',
  description: 'Standard page layout with content',
  templateType: 'single-page',
  category: 'theme-builder',
  relevantFor: ['ecommerce', 'blog', 'business', 'portfolio', 'landing', 'news'],
  icon: 'file',
  enabled: true,
  containerSettings: {
    content_width: { size: 800, unit: 'px' },
    gap: 'no',
    padding: { top: 60, right: 20, bottom: 60, left: 20, unit: 'px' },
  },
  widgetGroups: [
    {
      key: 'page-header',
      label: 'Page Header',
      description: 'Page title and breadcrumbs',
      min: 1,
      widgets: [
        {
          widgetType: 'page-title',
          label: 'Page Title',
          description: 'Dynamic page title',
          icon: 'type',
          required: true,
          defaultSettings: {
            html_tag: 'h1',
            size: { size: 36, unit: 'px' },
            align: 'left',
            color: '#1a1a2e',
            weight: '700',
          },
          dynamicTags: { title: '[elementor-tag id="" name="page-title" settings="%7B%22include_context%22%3A%22yes%22%7D"]' },
        },
        {
          widgetType: 'breadcrumbs',
          label: 'Breadcrumbs',
          description: 'Navigation breadcrumb trail',
          icon: 'chevrons-right',
          required: false,
          defaultSettings: {
            home_text: 'Home',
            show_home: 'yes',
            home_link: 'yes',
            hide_on_404: 'yes',
            separator_icon: 'fas fa-chevron-right',
            text_color: '#666666',
            link_color: '#4A90D9',
            size: { size: 14, unit: 'px' },
          },
        },
      ],
    },
    {
      key: 'page-content',
      label: 'Page Content',
      description: 'Main page content',
      min: 1,
      widgets: [
        {
          widgetType: 'post-content',
          label: 'Page Content',
          description: 'Dynamic page content',
          icon: 'align-left',
          required: true,
          defaultSettings: {
            editor: '',
            align: 'left',
            color: '#333333',
            size: { size: 16, unit: 'px' },
            drop_cap: 'no',
            word_count: 0,
          },
          dynamicTags: { content: '[elementor-tag id="" name="post-content" settings="%7B%22word_count%22%3A%220%22%7D"]' },
        },
      ],
    },
  ],
};
