import type { SectionTemplate } from './types.js';

export const HEADER_TEMPLATE: SectionTemplate = {
  key: 'header',
  label: 'Header',
  description: 'Site header with logo, navigation, and action buttons',
  templateType: 'header',
  category: 'basic',
  relevantFor: ['ecommerce', 'blog', 'business', 'portfolio', 'landing', 'news'],
  icon: 'layout-dashboard',
  enabled: true,
  containerSettings: {
    content_width: { size: 1140, unit: 'px' },
    gap: 'no',
    flex_direction: 'row',
    padding: { top: 15, right: 20, bottom: 15, left: 20, unit: 'px' },
    background_color: '#FFFFFF',
    box_shadow: '0px 0px 10px 0px rgba(0,0,0,0.1)',
  },
  widgetGroups: [
    {
      key: 'logo-area',
      label: 'Logo Area',
      description: 'Site logo and/or site title',
      min: 1,
      max: 2,
      widgets: [
        {
          widgetType: 'site-logo',
          label: 'Site Logo',
          description: 'WordPress site logo image',
          icon: 'image',
          required: true,
          defaultSettings: {
            image: { url: '', id: '', size: 'full', source: 'site' },
            width: { size: 180, unit: 'px' },
            align: 'left',
            link: { url: '{{home_url}}', is_external: 'no', nofollow: 'no' },
          },
          dynamicTags: { image: '[elementor-tag id="" name="site-logo" settings="%7B%22responsive%22%3A%22%22%7D"]' },
        },
        {
          widgetType: 'site-title',
          label: 'Site Title',
          description: 'WordPress site title heading',
          icon: 'text',
          required: false,
          defaultSettings: {
            title: '{{site_title}}',
            html_tag: 'h1',
            size: { size: 24, unit: 'px' },
            align: 'left',
            link: { url: '{{home_url}}', is_external: 'no', nofollow: 'no' },
          },
          dynamicTags: { title: '[elementor-tag id="" name="site-title" settings="%7B%22responsive%22%3A%22%22%7D"]' },
        },
      ],
    },
    {
      key: 'navigation',
      label: 'Navigation',
      description: 'Primary navigation menu',
      min: 1,
      max: 2,
      widgets: [
        {
          widgetType: 'nav-menu',
          label: 'Nav Menu',
          description: 'Standard navigation menu',
          icon: 'menu',
          required: true,
          defaultSettings: {
            menu: 'primary',
            layout: 'horizontal',
            align: 'right',
            pointer: 'underline',
            animation: 'fade',
            toggle: 'icon',
            show_toggle: 'yes',
            breakpoint: 'tablet',
            submenu_animation: 'slide',
            dropdown_position: 'below',
          },
        },
        {
          widgetType: 'mega-menu',
          label: 'Mega Menu',
          description: 'Full-width mega navigation menu',
          icon: 'layout-wide',
          required: false,
          defaultSettings: {
            menu: 'primary',
            layout: 'horizontal',
            pointer: 'underline',
            animation: 'fade',
            dropdown_position: 'below',
            mega_menu_width: 'full',
            toggle: 'icon',
          },
        },
      ],
    },
    {
      key: 'actions',
      label: 'Actions',
      description: 'Search, cart, and CTA buttons',
      max: 4,
      multi: true,
      widgets: [
        {
          widgetType: 'search-form',
          label: 'Search Bar',
          description: 'Live search form',
          icon: 'search',
          required: false,
          defaultSettings: {
            skin: 'full_screen',
            live_search: 'yes',
            min_characters: 3,
            results_per_page: 5,
            search_icon: 'yes',
            placeholder: 'Search...',
          },
        },
        {
          widgetType: 'woocommerce-menu-cart',
          label: 'Menu Cart',
          description: 'WooCommerce cart icon with count',
          icon: 'shopping-cart',
          required: false,
          defaultSettings: {
            icon: 'cart-medium',
            icon_size: { size: 24, unit: 'px' },
            items_indicator: 'bubble',
            items_indicator_text: '',
            show_subtotal: 'yes',
            view_cart_button: 'yes',
            checkout_button: 'yes',
            auto_open_cart: 'no',
          },
        },
        {
          widgetType: 'button',
          label: 'CTA Button',
          description: 'Call-to-action button',
          icon: 'square-mouse-pointer',
          required: false,
          defaultSettings: {
            text: 'Get Started',
            link: { url: '#', is_external: 'no', nofollow: 'no' },
            button_size: 'md',
            button_type: 'default',
            icon: '',
            icon_align: 'left',
            hover_animation: 'grow',
          },
        },
        {
          widgetType: 'login',
          label: 'Login/Register',
          description: 'Login or registration button',
          icon: 'log-in',
          required: false,
          defaultSettings: {
            redirect_url: '/my-account/',
            logout_redirect: '',
            show_lost_password: 'yes',
            show_remember_me: 'yes',
            show_logged_in_message: 'yes',
            custom_labels: 'no',
          },
        },
      ],
    },
  ],
};

export const HERO_TEMPLATE: SectionTemplate = {
  key: 'hero',
  label: 'Hero Section',
  description: 'Full-width hero with headline, subtext, and call-to-action',
  templateType: 'section',
  category: 'basic',
  relevantFor: ['ecommerce', 'blog', 'business', 'portfolio', 'landing', 'news'],
  icon: 'monitor',
  enabled: true,
  containerSettings: {
    content_width: { size: 1140, unit: 'px' },
    gap: 'no',
    min_height: { size: 600, unit: 'px' },
    flex_direction: 'column',
    align_items: 'center',
    justify_content: 'center',
    padding: { top: 100, right: 20, bottom: 100, left: 20, unit: 'px' },
    background_color: '#1a1a2e',
    background_image: { url: '', id: '', size: 'cover', source: 'library' },
    background_overlay: '#000000B0',
  },
  widgetGroups: [
    {
      key: 'media',
      label: 'Media',
      description: 'Background slideshow or video',
      max: 1,
      widgets: [
        {
          widgetType: 'slides',
          label: 'Slideshow',
          description: 'Full-screen slide carousel',
          icon: 'presentation',
          required: false,
          defaultSettings: {
            slides: [
              { _id: 'slide1', heading: 'Welcome', description: 'Your tagline here', button_text: 'Learn More', button_link: { url: '#', is_external: 'no', nofollow: 'no' }, background_image: { url: '', id: '', size: 'full', source: 'library' } },
              { _id: 'slide2', heading: 'Our Services', description: 'What we offer', button_text: 'View Services', button_link: { url: '#', is_external: 'no', nofollow: 'no' }, background_image: { url: '', id: '', size: 'full', source: 'library' } },
            ],
            navigation: 'arrows',
            slide_animation: 'fade',
            animation_speed: 700,
            slides_to_show: 1,
            autoplay: 'yes',
            autoplay_speed: 5000,
            pause_on_hover: 'yes',
            infinite: 'yes',
          },
        },
      ],
    },
    {
      key: 'content',
      label: 'Content',
      description: 'Headline, subtext, and buttons',
      min: 2,
      widgets: [
        {
          widgetType: 'heading',
          label: 'Headline',
          description: 'Main heading text',
          icon: 'type',
          required: true,
          defaultSettings: {
            title: 'Build Something Amazing',
            html_tag: 'h1',
            size: { size: 56, unit: 'px' },
            align: 'center',
            color: '#FFFFFF',
            weight: '700',
          },
        },
        {
          widgetType: 'text-editor',
          label: 'Subtext',
          description: 'Supporting description',
          icon: 'align-left',
          required: true,
          defaultSettings: {
            editor: '<p>Create stunning websites with our powerful platform. No coding required.</p>',
            align: 'center',
            color: '#CCCCCC',
            size: { size: 18, unit: 'px' },
            drop_cap: 'no',
          },
        },
        {
          widgetType: 'button',
          label: 'Primary Button',
          description: 'Main CTA button',
          icon: 'square-mouse-pointer',
          required: true,
          defaultSettings: {
            text: 'Get Started',
            link: { url: '#', is_external: 'no', nofollow: 'no' },
            button_size: 'lg',
            button_type: 'default',
            icon: '',
            icon_align: 'right',
            hover_animation: 'grow',
            button_background_color: '#4A90D9',
            button_text_color: '#FFFFFF',
          },
        },
        {
          widgetType: 'button',
          label: 'Secondary Button',
          description: 'Secondary CTA button',
          icon: 'square-mouse-pointer',
          required: false,
          defaultSettings: {
            text: 'Learn More',
            link: { url: '#', is_external: 'no', nofollow: 'no' },
            button_size: 'lg',
            button_type: 'outline',
            icon: '',
            icon_align: 'right',
            hover_animation: 'grow',
            button_background_color: 'transparent',
            button_text_color: '#FFFFFF',
            border_border: 'solid',
            border_width: { top: 2, right: 2, bottom: 2, left: 2, unit: 'px' },
            border_color: '#FFFFFF',
          },
        },
        {
          widgetType: 'animated-headline',
          label: 'Animated Headline',
          description: 'Headline with rotating or highlight animation',
          icon: 'text-cursor',
          required: false,
          defaultSettings: {
            headline_style: 'rotate',
            animated_text: 'Amazing, Beautiful, Powerful',
            rotating_text: ['Amazing', 'Beautiful', 'Powerful'],
            animation_duration: 1500,
            highlight_animation: 'none',
            html_tag: 'h1',
            size: { size: 48, unit: 'px' },
            align: 'center',
            color: '#FFFFFF',
          },
        },
      ],
    },
  ],
};
