import { SectionTemplate } from '../types.js';

export const CTA_BANNER_TEMPLATE: SectionTemplate = {
    key: 'cta-banner',
    label: 'CTA Banner',
    description: 'Full-width call-to-action banner',
    templateType: 'section',
    category: 'basic',
    relevantFor: ['ecommerce', 'blog', 'business', 'portfolio', 'landing'],
    icon: 'megaphone',
    enabled: true,
    containerSettings: {
      content_width: { size: 1140, unit: 'px' },
      gap: 'no',
      padding: { top: 80, right: 40, bottom: 80, left: 40, unit: 'px' },
      background_color: '#4A90D9',
      align_items: 'center',
      justify_content: 'center',
      flex_direction: 'column',
      min_height: { size: 300, unit: 'px' },
    },
    widgetGroups: [
      {
        key: 'cta-content',
        label: 'CTA Content',
        description: 'Title, description, and button',
        min: 2,
        widgets: [
          {
            widgetType: 'heading',
            label: 'CTA Title',
            icon: 'type',
            required: true,
            defaultSettings: {
              title: 'Ready to Get Started?',
              html_tag: 'h2',
              size: { size: 36, unit: 'px' },
              align: 'center',
              color: '#FFFFFF',
              weight: '700',
            },
          },
          {
            widgetType: 'text-editor',
            label: 'CTA Description',
            icon: 'align-left',
            required: false,
            defaultSettings: {
              editor: '<p>Join thousands of satisfied customers today.</p>',
              align: 'center',
              color: '#FFFFFFE0',
              size: { size: 18, unit: 'px' },
            },
          },
          {
            widgetType: 'button',
            label: 'CTA Button',
            icon: 'square-mouse-pointer',
            required: true,
            defaultSettings: {
              text: 'Get Started Free',
              link: { url: '#', is_external: 'no', nofollow: 'no' },
              button_size: 'lg',
              button_type: 'default',
              hover_animation: 'grow',
              button_background_color: '#FFFFFF',
              button_text_color: '#4A90D9',
              padding: { top: 15, right: 40, bottom: 15, left: 40, unit: 'px' },
              border_radius: { size: 50, unit: 'px' },
            },
          },
          {
            widgetType: 'call-to-action',
            label: 'Advanced CTA',
            description: 'Call to action with graphic',
            icon: 'megaphone',
            required: false,
            defaultSettings: {
              title: 'Limited Time Offer',
              description: 'Get 50% off your first month.',
              button_text: 'Claim Offer',
              button_link: { url: '#', is_external: 'no', nofollow: 'no' },
              graphic_element: 'icon',
              icon: 'gift',
              ribbon_title: 'Sale',
              cta_layout: 'standard',
              background_color: '#e74c3c',
              title_color: '#FFFFFF',
              description_color: '#FFFFFFE0',
              button_background_color: '#FFFFFF',
              button_text_color: '#e74c3c',
            },
          },
        ],
      },
    ],
  };

export const COUNTDOWN_TEMPLATE: SectionTemplate = {
    key: 'countdown',
    label: 'Countdown / Coming Soon',
    description: 'Countdown timer for launches or events',
    templateType: 'section',
    category: 'basic',
    relevantFor: ['business', 'landing', 'ecommerce'],
    icon: 'timer',
    enabled: true,
    containerSettings: {
      content_width: { size: 800, unit: 'px' },
      gap: 'no',
      padding: { top: 80, right: 20, bottom: 80, left: 20, unit: 'px' },
      align_items: 'center',
      justify_content: 'center',
      flex_direction: 'column',
      background_color: '#1a1a2e',
    },
    widgetGroups: [
      {
        key: 'countdown-content',
        label: 'Countdown Content',
        description: 'Heading, timer, and optional CTA',
        min: 1,
        widgets: [
          {
            widgetType: 'heading',
            label: 'Coming Soon Title',
            icon: 'type',
            required: true,
            defaultSettings: {
              title: 'Something Big Is Coming',
              html_tag: 'h2',
              size: { size: 48, unit: 'px' },
              align: 'center',
              color: '#FFFFFF',
              weight: '700',
            },
          },
          {
            widgetType: 'text-editor',
            label: 'Coming Soon Text',
            icon: 'align-left',
            required: false,
            defaultSettings: {
              editor: '<p>We are working on something amazing. Stay tuned!</p>',
              align: 'center',
              color: '#CCCCCC',
              size: { size: 18, unit: 'px' },
            },
          },
          {
            widgetType: 'countdown',
            label: 'Countdown Timer',
            description: 'Days, hours, minutes, seconds',
            icon: 'timer',
            required: true,
            defaultSettings: {
              countdown_type: 'due_date',
              due_date: '2026-12-31 23:59',
              evergreen_hours: 48,
              evergreen_minutes: 0,
              label_days: 'Days',
              label_hours: 'Hours',
              label_minutes: 'Minutes',
              label_seconds: 'Seconds',
              show_days: 'yes',
              show_hours: 'yes',
              show_minutes: 'yes',
              show_seconds: 'yes',
              box_background_color: '#333333',
              number_color: '#FFFFFF',
              label_color: '#CCCCCC',
            },
          },
          {
            widgetType: 'newsletter-form',
            label: 'Notify Me Form',
            description: 'Launch notification signup',
            icon: 'mail-plus',
            required: false,
            defaultSettings: {
              form_name: 'Coming Soon',
              form_fields: [
                { _id: 'cs1', field_type: 'email', field_label: 'Email', placeholder: 'your@email.com', required: 'yes', field_size: 'sm', width: '100' },
              ],
              submit_button_text: 'Notify Me',
              button_size: 'md',
              button_type: 'default',
              submit_actions: ['email'],
              email_to: '{admin_email}',
              email_subject: 'New Launch Subscriber',
            },
          },
        ],
      },
    ],
  };

export const FEATURES_TEMPLATE: SectionTemplate = {
    key: 'features',
    label: 'Features / Icon Grid',
    description: 'Feature highlights with icons in row/grid',
    templateType: 'section',
    category: 'basic',
    relevantFor: ['business', 'landing', 'portfolio'],
    icon: 'grip',
    enabled: true,
    containerSettings: {
      content_width: { size: 1140, unit: 'px' },
      gap: 'yes',
      gap_size: { size: 40, unit: 'px' },
      padding: { top: 80, right: 20, bottom: 80, left: 20, unit: 'px' },
      columns: 3,
    },
    widgetGroups: [
      {
        key: 'section-header',
        label: 'Section Header',
        description: 'Title and subtitle',
        min: 1,
        max: 2,
        widgets: [
          {
            widgetType: 'heading',
            label: 'Section Title',
            icon: 'type',
            required: true,
            defaultSettings: {
              title: 'Why Choose Us',
              html_tag: 'h2',
              size: { size: 36, unit: 'px' },
              align: 'center',
              color: '#1a1a2e',
              weight: '700',
            },
          },
          {
            widgetType: 'text-editor',
            label: 'Section Subtitle',
            icon: 'align-left',
            required: false,
            defaultSettings: {
              editor: '<p>Here\'s what sets us apart</p>',
              align: 'center',
              color: '#666666',
              size: { size: 18, unit: 'px' },
            },
          },
        ],
      },
      {
        key: 'feature-items',
        label: 'Feature Items',
        description: 'Icon+text feature cards',
        min: 3,
        multi: true,
        widgets: [
          {
            widgetType: 'icon',
            label: 'Feature Icon',
            description: 'Standalone icon',
            icon: 'circle',
            required: false,
            defaultSettings: {
              icon: 'star',
              view: 'default',
              icon_size: { size: 50, unit: 'px' },
              icon_color: '#4A90D9',
              icon_hover_color: '#1a1a2e',
              hover_animation: 'float',
              padding: { top: 15, right: 15, bottom: 15, left: 15, unit: 'px' },
              align: 'center',
            },
          },
          {
            widgetType: 'icon-box',
            label: 'Feature Box',
            description: 'Icon with title and description',
            icon: 'box',
            required: true,
            defaultSettings: {
              icon: 'zap',
              title_text: 'Lightning Fast',
              description_text: 'Optimized for speed and performance.',
              icon_size: { size: 40, unit: 'px' },
              icon_color: '#4A90D9',
              title_size: { size: 20, unit: 'px' },
              description_size: { size: 15, unit: 'px' },
              position: 'top',
              align: 'center',
              title_html_tag: 'h3',
              hover_animation: 'grow',
            },
          },
          {
            widgetType: 'icon-list',
            label: 'Feature List',
            description: 'Bulleted features with icons',
            icon: 'list',
            required: false,
            defaultSettings: {
              icon_list: [
                { _id: 'fl1', text: 'Feature one description', icon: 'check-circle', link: { url: '', is_external: 'no', nofollow: 'no' } },
                { _id: 'fl2', text: 'Feature two description', icon: 'check-circle', link: { url: '', is_external: 'no', nofollow: 'no' } },
                { _id: 'fl3', text: 'Feature three description', icon: 'check-circle', link: { url: '', is_external: 'no', nofollow: 'no' } },
              ],
              icon_size: { size: 18, unit: 'px' },
              icon_color: '#4A90D9',
              text_color: '#333333',
              text_size: { size: 16, unit: 'px' },
              icon_align: 'left',
            },
          },
        ],
      },
    ],
  };

export const STATS_TEMPLATE: SectionTemplate = {
    key: 'stats',
    label: 'Statistics Section',
    description: 'Animated counters and progress trackers',
    templateType: 'section',
    category: 'basic',
    relevantFor: ['business', 'portfolio', 'landing'],
    icon: 'bar-chart-3',
    enabled: true,
    containerSettings: {
      content_width: { size: 1140, unit: 'px' },
      gap: 'yes',
      gap_size: { size: 30, unit: 'px' },
      padding: { top: 80, right: 20, bottom: 80, left: 20, unit: 'px' },
      columns: 4,
      background_color: '#F8F9FA',
    },
    widgetGroups: [
      {
        key: 'section-header',
        label: 'Section Header',
        description: 'Title and subtitle',
        max: 2,
        widgets: [
          {
            widgetType: 'heading',
            label: 'Section Title',
            icon: 'type',
            required: true,
            defaultSettings: {
              title: 'By the Numbers',
              html_tag: 'h2',
              size: { size: 36, unit: 'px' },
              align: 'center',
              color: '#1a1a2e',
              weight: '700',
            },
          },
        ],
      },
      {
        key: 'stat-counters',
        label: 'Stat Counters',
        description: 'Animated number displays',
        min: 3,
        multi: true,
        widgets: [
          {
            widgetType: 'counter',
            label: 'Stat Counter',
            description: 'Animated number with label',
            icon: 'plus-circle',
            required: true,
            defaultSettings: {
              starting_number: 0,
              ending_number: 500,
              prefix: '',
              suffix: '+',
              title: 'Projects',
              icon: '',
              icon_size: { size: 40, unit: 'px' },
              number_size: { size: 48, unit: 'px' },
              title_size: { size: 18, unit: 'px' },
              align: 'center',
              number_color: '#4A90D9',
              title_color: '#333333',
              duration: 2000,
            },
          },
          {
            widgetType: 'progress-tracker',
            label: 'Progress Tracker',
            description: 'Circular or bar progress',
            icon: 'pie-chart',
            required: false,
            defaultSettings: {
              progress_type: 'circular',
              percent: 75,
              display_percentage: 'yes',
              percentage_text: '75%',
              inner_text: 'Complete',
              progress_color: '#4A90D9',
              background_color: '#E0E0E0',
            },
          },
        ],
      },
    ],
  };

export const VIDEO_TEMPLATE: SectionTemplate = {
    key: 'video',
    label: 'Video Section',
    description: 'Video showcase with playlist support',
    templateType: 'section',
    category: 'media',
    relevantFor: ['ecommerce', 'blog', 'business', 'portfolio', 'landing'],
    icon: 'video',
    enabled: true,
    containerSettings: {
      content_width: { size: 900, unit: 'px' },
      gap: 'no',
      padding: { top: 80, right: 20, bottom: 80, left: 20, unit: 'px' },
    },
    widgetGroups: [
      {
        key: 'section-header',
        label: 'Section Header',
        description: 'Title and subtitle',
        max: 2,
        widgets: [
          {
            widgetType: 'heading',
            label: 'Section Title',
            icon: 'type',
            required: true,
            defaultSettings: {
              title: 'Watch Our Video',
              html_tag: 'h2',
              size: { size: 36, unit: 'px' },
              align: 'center',
              color: '#1a1a2e',
              weight: '700',
            },
          },
        ],
      },
      {
        key: 'video-player',
        label: 'Video Player',
        description: 'Main video or playlist',
        max: 1,
        widgets: [
          {
            widgetType: 'video',
            label: 'Video Player',
            description: 'YouTube/Vimeo/hosted video',
            icon: 'youtube',
            required: true,
            defaultSettings: {
              video_type: 'youtube',
              youtube_url: 'https://www.youtube.com/watch?v=example',
              vimeo_url: '',
              host_video_url: '',
              autoplay: 'no',
              muted: 'no',
              loop: 'no',
              controls: 'yes',
              showinfo: 'yes',
              modestbranding: 'yes',
              aspect_ratio: '16:9',
              lightbox: 'no',
              image_overlay: { url: '', id: '', size: 'large', source: 'library' },
            },
          },
          {
            widgetType: 'video-playlist',
            label: 'Video Playlist',
            description: 'Multiple videos in playlist',
            icon: 'list-video',
            required: false,
            defaultSettings: {
              tabs: [
                { _id: 'vp1', type: 'youtube', url: 'https://www.youtube.com/watch?v=vid1', title: 'Introduction', duration: '5:30' },
                { _id: 'vp2', type: 'youtube', url: 'https://www.youtube.com/watch?v=vid2', title: 'Features Overview', duration: '8:15' },
                { _id: 'vp3', type: 'youtube', url: 'https://www.youtube.com/watch?v=vid3', title: 'Getting Started Guide', duration: '12:00' },
              ],
              playlist_title: 'Video Tutorials',
              aspect_ratio: '16:9',
            },
          },
        ],
      },
    ],
  };

export const MEDIA_CAROUSEL_TEMPLATE: SectionTemplate = {
    key: 'media-carousel',
    label: 'Media Carousel',
    description: 'Image and video carousel',
    templateType: 'section',
    category: 'media',
    relevantFor: ['ecommerce', 'portfolio', 'business', 'landing'],
    icon: 'chevrons-left-right',
    enabled: true,
    containerSettings: {
      content_width: { size: 1140, unit: 'px' },
      gap: 'no',
      padding: { top: 60, right: 20, bottom: 60, left: 20, unit: 'px' },
    },
    widgetGroups: [
      {
        key: 'carousel-content',
        label: 'Carousel',
        description: 'Image carousel widget',
        max: 1,
        widgets: [
          {
            widgetType: 'media-carousel',
            label: 'Media Carousel',
            description: 'Image/video carousel with navigation',
            icon: 'images',
            required: true,
            defaultSettings: {
              carousel_items: [
                { _id: 'mc1', image: { url: '', id: '', size: 'large', source: 'library' }, caption: '', link: { url: '', is_external: 'no', nofollow: 'no' } },
                { _id: 'mc2', image: { url: '', id: '', size: 'large', source: 'library' }, caption: '', link: { url: '', is_external: 'no', nofollow: 'no' } },
                { _id: 'mc3', image: { url: '', id: '', size: 'large', source: 'library' }, caption: '', link: { url: '', is_external: 'no', nofollow: 'no' } },
              ],
              slides_to_show: 3,
              slides_to_scroll: 1,
              image_size: 'large',
              image_fit: 'cover',
              autoplay: 'yes',
              autoplay_speed: 3000,
              pause_on_hover: 'yes',
              infinite: 'yes',
              navigation: 'arrows',
              aspect_ratio: '4:3',
            },
          },
          {
            widgetType: 'image-carousel',
            label: 'Image Carousel',
            description: 'Simple image carousel',
            icon: 'image',
            required: false,
            defaultSettings: {
              carousel: [],
              slides_to_show: 1,
              slides_to_scroll: 1,
              autoplay: 'yes',
              autoplay_speed: 3000,
              pause_on_hover: 'yes',
              infinite: 'yes',
              navigation: 'both',
            },
          },
          {
            widgetType: 'nested-carousel',
            label: 'Nested Carousel',
            description: 'Advanced nested carousel',
            icon: 'layers',
            required: false,
            defaultSettings: {
              slides_to_show: 3,
              slides_to_scroll: 1,
              autoplay: 'yes',
              autoplay_speed: 4000,
              pause_on_hover: 'yes',
              infinite: 'yes',
              navigation: 'arrows',
              image_size: 'medium',
              image_fit: 'cover',
            },
          },
        ],
      },
    ],
  };
