import type { ComponentClassification, ExtractedTokens, NavigationComponent } from '@typefigma/analyzer';

export const mockTokens: ExtractedTokens = {
  colors: {
    primary: { '500': '#1a1a2e' }, secondary: { '500': '#16213e' }, accent: { '500': '#0f3460' },
    neutral: { '50': '#f8f9fa', '500': '#737373', '900': '#1a1a2e' },
    success: { '500': '#22c55e' }, warning: { '500': '#eab308' }, error: { '500': '#ef4444' }, info: { '500': '#3b82f6' },
    background: { body: '#ffffff', surface: '#f8f9fa', overlay: '#0000004d' },
    text: { primary: '#333333', secondary: '#737373', disabled: '#a3a3a3', inverse: '#ffffff' },
    border: { default: '#e0e0e0', hover: '#d4d4d4', focus: '#3b82f6' },
  },
  typography: {
    fontFamilies: { heading: { name: 'system-ui', weights: [400, 600, 700], fallback: 'sans-serif' }, body: { name: 'system-ui', weights: [400, 500], fallback: 'sans-serif' } },
    fontSizes: { base: '1rem', lg: '1.125rem', xl: '1.25rem' },
    fontWeights: { normal: 400, semibold: 600, bold: 700 },
    lineHeights: { normal: 1.5, tight: 1.2 },
    letterSpacing: { normal: '0' },
    textStyles: {
      h1: { fontFamily: 'system-ui', fontSize: '3rem', fontWeight: 700, lineHeight: '1.2', letterSpacing: '0' },
      h2: { fontFamily: 'system-ui', fontSize: '2.25rem', fontWeight: 700, lineHeight: '1.2', letterSpacing: '0' },
      h3: { fontFamily: 'system-ui', fontSize: '1.5rem', fontWeight: 600, lineHeight: '1.2', letterSpacing: '0' },
      h4: { fontFamily: 'system-ui', fontSize: '1.25rem', fontWeight: 600, lineHeight: '1.2', letterSpacing: '0' },
      h5: { fontFamily: 'system-ui', fontSize: '1rem', fontWeight: 500, lineHeight: '1.2', letterSpacing: '0' },
      h6: { fontFamily: 'system-ui', fontSize: '0.875rem', fontWeight: 500, lineHeight: '1.2', letterSpacing: '0' },
      body: { fontFamily: 'system-ui', fontSize: '1rem', fontWeight: 400, lineHeight: '1.6', letterSpacing: '0' },
      bodyLarge: { fontFamily: 'system-ui', fontSize: '1.125rem', fontWeight: 400, lineHeight: '1.6', letterSpacing: '0' },
      bodySmall: { fontFamily: 'system-ui', fontSize: '0.875rem', fontWeight: 400, lineHeight: '1.6', letterSpacing: '0' },
      caption: { fontFamily: 'system-ui', fontSize: '0.75rem', fontWeight: 400, lineHeight: '1.5', letterSpacing: '0' },
      overline: { fontFamily: 'system-ui', fontSize: '0.75rem', fontWeight: 500, lineHeight: '1.5', letterSpacing: '0.05em', textTransform: 'uppercase' },
      button: { fontFamily: 'system-ui', fontSize: '0.875rem', fontWeight: 600, lineHeight: '1.5', letterSpacing: '0' },
    },
  },
  spacing: { '0': '0', '4': '1rem', '8': '2rem', section: '6rem' },
  sizing: { full: '100%', auto: 'auto', container: '1200px' },
  borderRadius: { none: '0', default: '0.375rem', full: '9999px' },
  shadows: { none: 'none', sm: '0 1px 2px 0 rgb(0 0 0 / 0.05)', md: '0 4px 6px -1px rgb(0 0 0 / 0.1)', lg: '0 10px 15px -3px rgb(0 0 0 / 0.1)' },
  borders: { width: { '0': '0', default: '1px', '2': '2px', '4': '4px' }, styles: { solid: 'solid', none: 'none' } },
  transitions: { duration: { base: '300ms' }, timing: { ease: 'ease' } },
  breakpoints: { sm: '640px', md: '768px', lg: '1024px', xl: '1280px' },
  zIndex: { '0': 0, '10': 10, auto: 'auto' },
};

/** Simple component tree: header + footer + hero */
export const simpleComponents: ComponentClassification = {
  headers: [{ id: 'h1', figmaNodeId: 'h1', name: 'Main Header', hasLogo: true, hasMenu: true, hasCTA: true, hasSearch: false, type: 'sticky', layout: { alignment: 'space-between', height: '80px', padding: { top: '16', right: '24', bottom: '16', left: '24' } }, confidence: 0.95 }],
  heroes: [{ id: 'hero1', figmaNodeId: 'hero1', name: 'Hero', layout: 'centered', hasVideo: false, hasSlider: false, hasOverlay: false, content: { hasHeadline: true, hasSubtext: true, hasButtons: true, hasImage: false }, confidence: 0.9 }],
  footers: [{ id: 'f1', figmaNodeId: 'f1', name: 'Footer', columns: 3, hasSocial: true, hasNewsletter: false, hasMenu: true, confidence: 0.95 }],
  navigation: [],
  sections: [],
  ctaSections: [],
  productCards: [],
  productDetails: [],
  cartComponents: [],
  checkoutComponents: [],
  searchBars: [],
  newsletters: [],
  contactForms: [],
  testimonials: [],
  galleries: [],
  postCards: [],
  postDetail: [],
  containers: [],
  columns: [],
  responsiveBreakpoints: [],
  interactionStates: [],
};

/** Nested component tree: sections with containers and columns */
export const nestedComponents: ComponentClassification = {
  headers: [],
  heroes: [],
  footers: [{ id: 'f1', figmaNodeId: 'f1', name: 'Site Footer', columns: 2, hasSocial: true, hasNewsletter: true, hasMenu: true, confidence: 0.85 }],
  navigation: [{ id: 'n1', figmaNodeId: 'n1', type: 'horizontal', items: 5, hasDropdown: true } as NavigationComponent],
  sections: [
    { id: 's1', figmaNodeId: 's1', name: 'Features Section', type: 'features', confidence: 0.8, hasGrid: true, layout: { fullWidth: false, hasContainer: true, padding: { top: '4rem', right: '0', bottom: '4rem', left: '0' } } },
    { id: 's2', figmaNodeId: 's2', name: 'Testimonials Section', type: 'testimonials', confidence: 0.75, hasGrid: true, layout: { fullWidth: false, hasContainer: true, padding: { top: '4rem', right: '0', bottom: '4rem', left: '0' } } },
  ],
  containers: [
    { id: 'c1', figmaNodeId: 'c1', type: 'flex', direction: 'row', gap: '2rem' },
    { id: 'c2', figmaNodeId: 'c2', type: 'grid', gap: '1rem' },
  ],
  columns: [
    { id: 'col1', figmaNodeId: 'col1', span: 1, width: '25%' },
    { id: 'col2', figmaNodeId: 'col2', span: 2, width: '50%' },
    { id: 'col3', figmaNodeId: 'col3', span: 1, width: '25%' },
  ],
  ctaSections: [],
  productCards: [],
  productDetails: [],
  cartComponents: [],
  checkoutComponents: [],
  searchBars: [{ id: 'sb1', figmaNodeId: 'sb1', type: 'inline', hasDropdown: false, hasCategories: false }],
  newsletters: [{ id: 'nl1', figmaNodeId: 'nl1', hasName: true, hasEmail: true, hasConsentCheckbox: true }],
  contactForms: [],
  testimonials: [{ id: 't1', figmaNodeId: 't1', confidence: 0.8, layout: 'grid', hasAvatar: true, hasRating: true, hasCompanyLogo: false }],
  galleries: [{ id: 'g1', figmaNodeId: 'g1', layout: 'grid', imageCount: 6, hasLightbox: true, hasFilter: false }],
  postCards: [],
  postDetail: [],
  responsiveBreakpoints: [],
  interactionStates: [],
};

/** WooCommerce component tree: product cards + details + cart + checkout */
export const wcComponents: ComponentClassification = {
  headers: [{ id: 'h1', figmaNodeId: 'wc-h1', name: 'Shop Header', hasLogo: true, hasMenu: true, hasCTA: false, hasSearch: true, type: 'sticky', layout: { alignment: 'space-between', height: '80px', padding: { top: '16', right: '24', bottom: '16', left: '24' } }, confidence: 0.9 }],
  heroes: [],
  footers: [{ id: 'f1', figmaNodeId: 'wc-f1', name: 'Shop Footer', columns: 4, hasSocial: true, hasNewsletter: true, hasMenu: true, confidence: 0.85 }],
  navigation: [],
  sections: [],
  ctaSections: [{ id: 'cta1', figmaNodeId: 'wc-cta1', confidence: 0.75, type: 'banner', hasButton: true, hasImage: true }],
  productCards: [
    {
      id: 'pc1', figmaNodeId: 'wc-pc1', name: 'Product Card 1', confidence: 0.95,
      structure: {
        productImage: { nodeId: 'wc-pc1-img', aspectRatio: '1:1', hasBorderRadius: true, hasHoverEffect: true },
        productTitle: { nodeId: 'wc-pc1-title', maxLines: 2 },
        productPrice: { nodeId: 'wc-pc1-price', format: 'sale', hasCurrency: true },
        addToCartButton: { nodeId: 'wc-pc1-atc', text: 'Add to Cart' },
      },
      layout: { type: 'card', alignment: 'center', spacing: { top: '1rem', right: '1rem', bottom: '1rem', left: '1rem' }, containerPadding: { top: '1rem', right: '1rem', bottom: '1rem', left: '1rem' } },
    },
    {
      id: 'pc2', figmaNodeId: 'wc-pc2', name: 'Product Card 2', confidence: 0.92,
      structure: {
        productImage: { nodeId: 'wc-pc2-img', aspectRatio: '1:1', hasBorderRadius: true, hasHoverEffect: true },
        productTitle: { nodeId: 'wc-pc2-title', maxLines: 2 },
        productPrice: { nodeId: 'wc-pc2-price', format: 'regular', hasCurrency: true },
        addToCartButton: { nodeId: 'wc-pc2-atc', text: 'Add to Cart' },
      },
      layout: { type: 'card', alignment: 'center', spacing: { top: '1rem', right: '1rem', bottom: '1rem', left: '1rem' }, containerPadding: { top: '1rem', right: '1rem', bottom: '1rem', left: '1rem' } },
    },
  ],
  productDetails: [{
    id: 'pd1', figmaNodeId: 'wc-pd1', confidence: 0.88,
    layout: 'sidebar-right',
    sections: {
      productGallery: { nodeId: 'wc-pd1-gallery', type: 'thumbnails-bottom', hasZoom: true, hasLightbox: true },
      productMeta: {
        title: { nodeId: 'wc-pd1-title', tag: 'h1' },
        price: { nodeId: 'wc-pd1-price', showSalePrice: true, showSavings: true },
        rating: { nodeId: 'wc-pd1-rating', showCount: true, linkToReviews: true },
        availability: { nodeId: 'wc-pd1-avail' },
      },
      shortDescription: { nodeId: 'wc-pd1-desc' },
      addToCart: {
        quantitySelector: { nodeId: 'wc-pd1-qty', style: 'input' },
        addToCartButton: { nodeId: 'wc-pd1-atc', text: 'Add to Cart' },
      },
      productActions: { share: { platforms: ['facebook', 'twitter'] } },
      productTabs: { nodeId: 'wc-pd1-tabs', type: 'tabs', hasDescription: true, hasAdditionalInfo: true, hasReviews: true },
    },
  }],
  cartComponents: [{ id: 'cart1', figmaNodeId: 'wc-cart1', confidence: 0.9, type: 'full-cart', hasQuantityControl: true, hasRemoveButton: true, hasCouponInput: true, hasProceedToCheckout: true }],
  checkoutComponents: [{ id: 'chk1', figmaNodeId: 'wc-chk1', confidence: 0.85, layout: 'two-column', hasBillingForm: true, hasShippingForm: true, hasOrderSummary: true, hasPaymentMethods: true }],
  searchBars: [],
  newsletters: [],
  contactForms: [],
  testimonials: [],
  galleries: [],
  postCards: [],
  postDetail: [],
  containers: [],
  columns: [],
  responsiveBreakpoints: [],
  interactionStates: [],
};
